/*
 * Internal module API header file.
 *
 * Generated by SIP 4.19.12
 */

#ifndef _qcamotorAPI_H
#define _qcamotorAPI_H

#include <sip.h>

#include <QMetaType>
#include <QThread>

/* These are the qualifiers that are enabled. */
#define SIP_FEATURE_PyQt_MacOSXOnly
#define SIP_FEATURE_PyQt_Process
#define SIP_FEATURE_PyQt_NotBootstrapped
#define SIP_FEATURE_PyQt_Desktop_OpenGL
#define SIP_FEATURE_PyQt_OpenGL
#define SIP_FEATURE_PyQt_RawFont
#define SIP_FEATURE_PyQt_PrintPreviewDialog
#define SIP_FEATURE_PyQt_PrintPreviewWidget
#define SIP_FEATURE_PyQt_Printer
#define SIP_FEATURE_PyQt_PrintDialog
#define SIP_FEATURE_Py_v3
#define SIP_FEATURE_PyQt_qreal_double
#define SIP_FEATURE_PyQt_SSL
#define SIP_FEATURE_PyQt_SessionManager
#define SIP_FEATURE_PyQt_Accessibility
#define SIP_PLATFORM_WS_X11


/*
 * Convenient names to refer to various strings defined in this module.
 * Only the class names are part of the public API.
 */
#define sipNameNr_changedBacklashAcceleration 0
#define sipName_changedBacklashAcceleration &sipStrings_qcamotor[0]
#define sipNameNr_changedReadbackResolution 28
#define sipName_changedReadbackResolution &sipStrings_qcamotor[28]
#define sipNameNr_changedEncoderResolution 54
#define sipName_changedEncoderResolution &sipStrings_qcamotor[54]
#define sipNameNr_setBacklashAcceleration 79
#define sipName_setBacklashAcceleration &sipStrings_qcamotor[79]
#define sipNameNr_getBacklashAcceleration 103
#define sipName_getBacklashAcceleration &sipStrings_qcamotor[103]
#define sipNameNr_changedPowerConnection 127
#define sipName_changedPowerConnection &sipStrings_qcamotor[127]
#define sipNameNr_changedJogAcceleration 150
#define sipName_changedJogAcceleration &sipStrings_qcamotor[150]
#define sipNameNr_changedMotorResolution 173
#define sipName_changedMotorResolution &sipStrings_qcamotor[173]
#define sipNameNr_setReadbackResolution 196
#define sipName_setReadbackResolution &sipStrings_qcamotor[196]
#define sipNameNr_getReadbackResolution 218
#define sipName_getReadbackResolution &sipStrings_qcamotor[218]
#define sipNameNr_changedBacklashSpeed 240
#define sipName_changedBacklashSpeed &sipStrings_qcamotor[240]
#define sipNameNr_changedLoLimitStatus 261
#define sipName_changedLoLimitStatus &sipStrings_qcamotor[261]
#define sipNameNr_changedHiLimitStatus 282
#define sipName_changedHiLimitStatus &sipStrings_qcamotor[282]
#define sipNameNr_setEncoderResolution 303
#define sipName_setEncoderResolution &sipStrings_qcamotor[303]
#define sipNameNr_getEncoderResolution 324
#define sipName_getEncoderResolution &sipStrings_qcamotor[324]
#define sipNameNr_QCaMotor__MotionExit 345
#define sipName_QCaMotor__MotionExit &sipStrings_qcamotor[345]
#define sipNameNr_changedAcceleration 366
#define sipName_changedAcceleration &sipStrings_qcamotor[366]
#define sipNameNr_changedMaximumSpeed 386
#define sipName_changedMaximumSpeed &sipStrings_qcamotor[386]
#define sipNameNr_changedDialPosition 406
#define sipName_changedDialPosition &sipStrings_qcamotor[406]
#define sipNameNr_changedUserPosition 426
#define sipName_changedUserPosition &sipStrings_qcamotor[426]
#define sipNameNr_QCaMotor__Direction 446
#define sipName_QCaMotor__Direction &sipStrings_qcamotor[446]
#define sipNameNr_changedUseReadback 466
#define sipName_changedUseReadback &sipStrings_qcamotor[466]
#define sipNameNr_changedNormalSpeed 485
#define sipName_changedNormalSpeed &sipStrings_qcamotor[485]
#define sipNameNr_changedStepsPerRev 504
#define sipName_changedStepsPerRev &sipStrings_qcamotor[504]
#define sipNameNr_changedUnitsPerRev 523
#define sipName_changedUnitsPerRev &sipStrings_qcamotor[523]
#define sipNameNr_changedDialHiLimit 542
#define sipName_changedDialHiLimit &sipStrings_qcamotor[542]
#define sipNameNr_changedDialLoLimit 561
#define sipName_changedDialLoLimit &sipStrings_qcamotor[561]
#define sipNameNr_changedUserLoLimit 580
#define sipName_changedUserLoLimit &sipStrings_qcamotor[580]
#define sipNameNr_changedUserHiLimit 599
#define sipName_changedUserHiLimit &sipStrings_qcamotor[599]
#define sipNameNr_changedRawPosition 618
#define sipName_changedRawPosition &sipStrings_qcamotor[618]
#define sipNameNr_changedDescription 637
#define sipName_changedDescription &sipStrings_qcamotor[637]
#define sipNameNr_setJogAcceleration 656
#define sipName_setJogAcceleration &sipStrings_qcamotor[656]
#define sipNameNr_setMotorResolution 675
#define sipName_setMotorResolution &sipStrings_qcamotor[675]
#define sipNameNr_getPowerConnection 694
#define sipName_getPowerConnection &sipStrings_qcamotor[694]
#define sipNameNr_getJogAcceleration 713
#define sipName_getJogAcceleration &sipStrings_qcamotor[713]
#define sipNameNr_getMotorResolution 732
#define sipName_getMotorResolution &sipStrings_qcamotor[732]
#define sipNameNr_QCaMotor__SpmgMode 751
#define sipName_QCaMotor__SpmgMode &sipStrings_qcamotor[751]
#define sipNameNr_changedUseEncoder 770
#define sipName_changedUseEncoder &sipStrings_qcamotor[770]
#define sipNameNr_changedOffsetMode 788
#define sipName_changedOffsetMode &sipStrings_qcamotor[788]
#define sipNameNr_loadConfiguration 806
#define sipName_loadConfiguration &sipStrings_qcamotor[806]
#define sipNameNr_saveConfiguration 824
#define sipName_saveConfiguration &sipStrings_qcamotor[824]
#define sipNameNr_QCaMotor__OffMode 842
#define sipName_QCaMotor__OffMode &sipStrings_qcamotor[842]
#define sipNameNr_isSignalConnected 860
#define sipName_isSignalConnected &sipStrings_qcamotor[860]
#define sipNameNr_senderSignalIndex 878
#define sipName_senderSignalIndex &sipStrings_qcamotor[878]
#define sipNameNr_changedConnected 896
#define sipName_changedConnected &sipStrings_qcamotor[896]
#define sipNameNr_changedDirection 913
#define sipName_changedDirection &sipStrings_qcamotor[913]
#define sipNameNr_changedPrecision 930
#define sipName_changedPrecision &sipStrings_qcamotor[930]
#define sipNameNr_setBacklashSpeed 947
#define sipName_setBacklashSpeed &sipStrings_qcamotor[947]
#define sipNameNr_getBacklashSpeed 964
#define sipName_getBacklashSpeed &sipStrings_qcamotor[964]
#define sipNameNr_getLoLimitStatus 981
#define sipName_getLoLimitStatus &sipStrings_qcamotor[981]
#define sipNameNr_getHiLimitStatus 998
#define sipName_getHiLimitStatus &sipStrings_qcamotor[998]
#define sipNameNr_QCaMotor__SuMode 1015
#define sipName_QCaMotor__SuMode &sipStrings_qcamotor[1015]
#define sipNameNr_disconnectNotify 1032
#define sipName_disconnectNotify &sipStrings_qcamotor[1032]
#define sipNameNr_changedSpmgMode 1049
#define sipName_changedSpmgMode &sipStrings_qcamotor[1049]
#define sipNameNr_changedBacklash 1065
#define sipName_changedBacklash &sipStrings_qcamotor[1065]
#define sipNameNr_changedJogSpeed 1081
#define sipName_changedJogSpeed &sipStrings_qcamotor[1081]
#define sipNameNr_changedRevSpeed 1097
#define sipName_changedRevSpeed &sipStrings_qcamotor[1097]
#define sipNameNr_changedDeadBand 1113
#define sipName_changedDeadBand &sipStrings_qcamotor[1113]
#define sipNameNr_changedDialGoal 1129
#define sipName_changedDialGoal &sipStrings_qcamotor[1129]
#define sipNameNr_changedUserGoal 1145
#define sipName_changedUserGoal &sipStrings_qcamotor[1145]
#define sipNameNr_setAcceleration 1161
#define sipName_setAcceleration &sipStrings_qcamotor[1161]
#define sipNameNr_setMaximumSpeed 1177
#define sipName_setMaximumSpeed &sipStrings_qcamotor[1177]
#define sipNameNr_setDialPosition 1193
#define sipName_setDialPosition &sipStrings_qcamotor[1193]
#define sipNameNr_setUserPosition 1209
#define sipName_setUserPosition &sipStrings_qcamotor[1209]
#define sipNameNr_getAcceleration 1225
#define sipName_getAcceleration &sipStrings_qcamotor[1225]
#define sipNameNr_getMaximumSpeed 1241
#define sipName_getMaximumSpeed &sipStrings_qcamotor[1241]
#define sipNameNr_getDialPosition 1257
#define sipName_getDialPosition &sipStrings_qcamotor[1257]
#define sipNameNr_getUserPosition 1273
#define sipName_getUserPosition &sipStrings_qcamotor[1273]
#define sipNameNr_changedRawGoal 1289
#define sipName_changedRawGoal &sipStrings_qcamotor[1289]
#define sipNameNr_setUseReadback 1304
#define sipName_setUseReadback &sipStrings_qcamotor[1304]
#define sipNameNr_setNormalSpeed 1319
#define sipName_setNormalSpeed &sipStrings_qcamotor[1319]
#define sipNameNr_setStepsPerRev 1334
#define sipName_setStepsPerRev &sipStrings_qcamotor[1334]
#define sipNameNr_setUnitsPerRev 1349
#define sipName_setUnitsPerRev &sipStrings_qcamotor[1349]
#define sipNameNr_setDialLoLimit 1364
#define sipName_setDialLoLimit &sipStrings_qcamotor[1364]
#define sipNameNr_setDialHiLimit 1379
#define sipName_setDialHiLimit &sipStrings_qcamotor[1379]
#define sipNameNr_setUserLoLimit 1394
#define sipName_setUserLoLimit &sipStrings_qcamotor[1394]
#define sipNameNr_setUserHiLimit 1409
#define sipName_setUserHiLimit &sipStrings_qcamotor[1409]
#define sipNameNr_undoLastMotion 1424
#define sipName_undoLastMotion &sipStrings_qcamotor[1424]
#define sipNameNr_goDialPosition 1439
#define sipName_goDialPosition &sipStrings_qcamotor[1439]
#define sipNameNr_goUserPosition 1454
#define sipName_goUserPosition &sipStrings_qcamotor[1454]
#define sipNameNr_setRawPosition 1469
#define sipName_setRawPosition &sipStrings_qcamotor[1469]
#define sipNameNr_getUseReadback 1484
#define sipName_getUseReadback &sipStrings_qcamotor[1484]
#define sipNameNr_getNormalSpeed 1499
#define sipName_getNormalSpeed &sipStrings_qcamotor[1499]
#define sipNameNr_getStepsPerRev 1514
#define sipName_getStepsPerRev &sipStrings_qcamotor[1514]
#define sipNameNr_getUnitsPerRev 1529
#define sipName_getUnitsPerRev &sipStrings_qcamotor[1529]
#define sipNameNr_getDialHiLimit 1544
#define sipName_getDialHiLimit &sipStrings_qcamotor[1544]
#define sipNameNr_getDialLoLimit 1559
#define sipName_getDialLoLimit &sipStrings_qcamotor[1559]
#define sipNameNr_getUserLoLimit 1574
#define sipName_getUserLoLimit &sipStrings_qcamotor[1574]
#define sipNameNr_getUserHiLimit 1589
#define sipName_getUserHiLimit &sipStrings_qcamotor[1589]
#define sipNameNr_getLimitStatus 1604
#define sipName_getLimitStatus &sipStrings_qcamotor[1604]
#define sipNameNr_getRawPosition 1619
#define sipName_getRawPosition &sipStrings_qcamotor[1619]
#define sipNameNr_getDescription 1634
#define sipName_getDescription &sipStrings_qcamotor[1634]
#define sipNameNr_setDescription 1649
#define sipName_setDescription &sipStrings_qcamotor[1649]
#define sipNameNr_changedMoving 1664
#define sipName_changedMoving &sipStrings_qcamotor[1664]
#define sipNameNr_changedSuMode 1678
#define sipName_changedSuMode &sipStrings_qcamotor[1678]
#define sipNameNr_changedOffset 1692
#define sipName_changedOffset &sipStrings_qcamotor[1692]
#define sipNameNr_setUseEncoder 1706
#define sipName_setUseEncoder &sipStrings_qcamotor[1706]
#define sipNameNr_setOffsetMode 1720
#define sipName_setOffsetMode &sipStrings_qcamotor[1720]
#define sipNameNr_goRawPosition 1734
#define sipName_goRawPosition &sipStrings_qcamotor[1734]
#define sipNameNr_getUseEncoder 1748
#define sipName_getUseEncoder &sipStrings_qcamotor[1748]
#define sipNameNr_getOffsetMode 1762
#define sipName_getOffsetMode &sipStrings_qcamotor[1762]
#define sipNameNr_getLastMotion 1776
#define sipName_getLastMotion &sipStrings_qcamotor[1776]
#define sipNameNr_connectNotify 1035
#define sipName_connectNotify &sipStrings_qcamotor[1035]
#define sipNameNr_changedWired 1790
#define sipName_changedWired &sipStrings_qcamotor[1790]
#define sipNameNr_changedPower 1803
#define sipName_changedPower &sipStrings_qcamotor[1803]
#define sipNameNr_changedUnits 1816
#define sipName_changedUnits &sipStrings_qcamotor[1816]
#define sipNameNr_setPrecision 1829
#define sipName_setPrecision &sipStrings_qcamotor[1829]
#define sipNameNr_getDirection 1842
#define sipName_getDirection &sipStrings_qcamotor[1842]
#define sipNameNr_getPrecision 1855
#define sipName_getPrecision &sipStrings_qcamotor[1855]
#define sipNameNr_CONFIRMATION 1868
#define sipName_CONFIRMATION &sipStrings_qcamotor[1868]
#define sipNameNr_setDirection 1881
#define sipName_setDirection &sipStrings_qcamotor[1881]
#define sipNameNr_changedStep 1894
#define sipName_changedStep &sipStrings_qcamotor[1894]
#define sipNameNr_setSpmgMode 1906
#define sipName_setSpmgMode &sipStrings_qcamotor[1906]
#define sipNameNr_setBacklash 1918
#define sipName_setBacklash &sipStrings_qcamotor[1918]
#define sipNameNr_setJogSpeed 1930
#define sipName_setJogSpeed &sipStrings_qcamotor[1930]
#define sipNameNr_setRevSpeed 1942
#define sipName_setRevSpeed &sipStrings_qcamotor[1942]
#define sipNameNr_setDeadBand 1954
#define sipName_setDeadBand &sipStrings_qcamotor[1954]
#define sipNameNr_getSpmgMode 1966
#define sipName_getSpmgMode &sipStrings_qcamotor[1966]
#define sipNameNr_getBacklash 1978
#define sipName_getBacklash &sipStrings_qcamotor[1978]
#define sipNameNr_isConnected 1990
#define sipName_isConnected &sipStrings_qcamotor[1990]
#define sipNameNr_getJogSpeed 2002
#define sipName_getJogSpeed &sipStrings_qcamotor[2002]
#define sipNameNr_getRevSpeed 2014
#define sipName_getRevSpeed &sipStrings_qcamotor[2014]
#define sipNameNr_getDeadBand 2026
#define sipName_getDeadBand &sipStrings_qcamotor[2026]
#define sipNameNr_getDialGoal 2038
#define sipName_getDialGoal &sipStrings_qcamotor[2038]
#define sipNameNr_getUserGoal 2050
#define sipName_getUserGoal &sipStrings_qcamotor[2050]
#define sipNameNr_ACCELERATED 2062
#define sipName_ACCELERATED &sipStrings_qcamotor[2062]
#define sipNameNr_IMMIDIATELY 2074
#define sipName_IMMIDIATELY &sipStrings_qcamotor[2074]
#define sipNameNr_customEvent 2086
#define sipName_customEvent &sipStrings_qcamotor[2086]
#define sipNameNr_eventFilter 2098
#define sipName_eventFilter &sipStrings_qcamotor[2098]
#define sipNameNr_printError 2110
#define sipName_printError &sipStrings_qcamotor[2110]
#define sipNameNr_goRelative 2121
#define sipName_goRelative &sipStrings_qcamotor[2121]
#define sipNameNr_getRawGoal 2132
#define sipName_getRawGoal &sipStrings_qcamotor[2132]
#define sipNameNr_wait_start 2143
#define sipName_wait_start &sipStrings_qcamotor[2143]
#define sipNameNr_MotionExit 355
#define sipName_MotionExit &sipStrings_qcamotor[355]
#define sipNameNr_childEvent 2154
#define sipName_childEvent &sipStrings_qcamotor[2154]
#define sipNameNr_timerEvent 2165
#define sipName_timerEvent &sipStrings_qcamotor[2165]
#define sipNameNr_changedPv 2176
#define sipName_changedPv &sipStrings_qcamotor[2176]
#define sipNameNr_setSuMode 2186
#define sipName_setSuMode &sipStrings_qcamotor[2186]
#define sipNameNr_setOffset 2196
#define sipName_setOffset &sipStrings_qcamotor[2196]
#define sipNameNr_getSuMode 2206
#define sipName_getSuMode &sipStrings_qcamotor[2206]
#define sipNameNr_getOffset 2216
#define sipName_getOffset &sipStrings_qcamotor[2216]
#define sipNameNr_wait_stop 2226
#define sipName_wait_stop &sipStrings_qcamotor[2226]
#define sipNameNr_directory 2236
#define sipName_directory &sipStrings_qcamotor[2236]
#define sipNameNr_receivers 2246
#define sipName_receivers &sipStrings_qcamotor[2246]
#define sipNameNr_precision 2256
#define sipName_precision &sipStrings_qcamotor[2256]
#define sipNameNr_Direction 456
#define sipName_Direction &sipStrings_qcamotor[456]
#define sipNameNr_setPower 2266
#define sipName_setPower &sipStrings_qcamotor[2266]
#define sipNameNr_setUnits 2275
#define sipName_setUnits &sipStrings_qcamotor[2275]
#define sipNameNr_getPower 2284
#define sipName_getPower &sipStrings_qcamotor[2284]
#define sipNameNr_isMoving 2293
#define sipName_isMoving &sipStrings_qcamotor[2293]
#define sipNameNr_getUnits 2302
#define sipName_getUnits &sipStrings_qcamotor[2302]
#define sipNameNr_NEGATIVE 2311
#define sipName_NEGATIVE &sipStrings_qcamotor[2311]
#define sipNameNr_POSITIVE 2320
#define sipName_POSITIVE &sipStrings_qcamotor[2320]
#define sipNameNr_VARIABLE 2329
#define sipName_VARIABLE &sipStrings_qcamotor[2329]
#define sipNameNr_SpmgMode 761
#define sipName_SpmgMode &sipStrings_qcamotor[761]
#define sipNameNr_QCaMotor 2338
#define sipName_QCaMotor &sipStrings_qcamotor[2338]
#define sipNameNr_nameType 2347
#define sipName_nameType &sipStrings_qcamotor[2347]
#define sipNameNr_qcamotor 2356
#define sipName_qcamotor &sipStrings_qcamotor[2356]
#define sipNameNr_setStep 2365
#define sipName_setStep &sipStrings_qcamotor[2365]
#define sipNameNr_goLimit 2373
#define sipName_goLimit &sipStrings_qcamotor[2373]
#define sipNameNr_isWired 2381
#define sipName_isWired &sipStrings_qcamotor[2381]
#define sipNameNr_getStep 2389
#define sipName_getStep &sipStrings_qcamotor[2389]
#define sipNameNr_STOPPED 2397
#define sipName_STOPPED &sipStrings_qcamotor[2397]
#define sipNameNr_STARTED 2405
#define sipName_STARTED &sipStrings_qcamotor[2405]
#define sipNameNr_OffMode 852
#define sipName_OffMode &sipStrings_qcamotor[852]
#define sipNameNr_stopped 2413
#define sipName_stopped &sipStrings_qcamotor[2413]
#define sipNameNr_filters 2421
#define sipName_filters &sipStrings_qcamotor[2421]
#define sipNameNr_enabled 2429
#define sipName_enabled &sipStrings_qcamotor[2429]
#define sipNameNr_options 2437
#define sipName_options &sipStrings_qcamotor[2437]
#define sipNameNr_goHome 2445
#define sipName_goHome &sipStrings_qcamotor[2445]
#define sipNameNr_goStep 2452
#define sipName_goStep &sipStrings_qcamotor[2452]
#define sipNameNr_FROZEN 2459
#define sipName_FROZEN &sipStrings_qcamotor[2459]
#define sipNameNr_SuMode 1025
#define sipName_SuMode &sipStrings_qcamotor[1025]
#define sipNameNr_proper 2466
#define sipName_proper &sipStrings_qcamotor[2466]
#define sipNameNr_sender 2473
#define sipName_sender &sipStrings_qcamotor[2473]
#define sipNameNr_value9 2480
#define sipName_value9 &sipStrings_qcamotor[2480]
#define sipNameNr_value8 2487
#define sipName_value8 &sipStrings_qcamotor[2487]
#define sipNameNr_value7 2494
#define sipName_value7 &sipStrings_qcamotor[2494]
#define sipNameNr_value6 2501
#define sipName_value6 &sipStrings_qcamotor[2501]
#define sipNameNr_value5 2508
#define sipName_value5 &sipStrings_qcamotor[2508]
#define sipNameNr_value4 2515
#define sipName_value4 &sipStrings_qcamotor[2515]
#define sipNameNr_value3 2522
#define sipName_value3 &sipStrings_qcamotor[2522]
#define sipNameNr_value2 2529
#define sipName_value2 &sipStrings_qcamotor[2529]
#define sipNameNr_value1 2536
#define sipName_value1 &sipStrings_qcamotor[2536]
#define sipNameNr_value0 2543
#define sipName_value0 &sipStrings_qcamotor[2543]
#define sipNameNr_symbol 2550
#define sipName_symbol &sipStrings_qcamotor[2550]
#define sipNameNr_suffix 2557
#define sipName_suffix &sipStrings_qcamotor[2557]
#define sipNameNr_prefix 2564
#define sipName_prefix &sipStrings_qcamotor[2564]
#define sipNameNr_locale 2571
#define sipName_locale &sipStrings_qcamotor[2571]
#define sipNameNr_format 2578
#define sipName_format &sipStrings_qcamotor[2578]
#define sipNameNr_object 2585
#define sipName_object &sipStrings_qcamotor[2585]
#define sipNameNr_setPv 2592
#define sipName_setPv &sipStrings_qcamotor[2592]
#define sipNameNr_getPv 2598
#define sipName_getPv &sipStrings_qcamotor[2598]
#define sipNameNr_PAUSE 2604
#define sipName_PAUSE &sipStrings_qcamotor[2604]
#define sipNameNr_error 2610
#define sipName_error &sipStrings_qcamotor[2610]
#define sipNameNr_event 2616
#define sipName_event &sipStrings_qcamotor[2616]
#define sipNameNr_msecs 2622
#define sipName_msecs &sipStrings_qcamotor[2622]
#define sipNameNr_MOVE 2628
#define sipName_MOVE &sipStrings_qcamotor[2628]
#define sipNameNr_STOP 2633
#define sipName_STOP &sipStrings_qcamotor[2633]
#define sipNameNr_mode 2638
#define sipName_mode &sipStrings_qcamotor[2638]
#define sipNameNr_name 2643
#define sipName_name &sipStrings_qcamotor[2643]
#define sipNameNr_base 2648
#define sipName_base &sipStrings_qcamotor[2648]
#define sipNameNr_from 2653
#define sipName_from &sipStrings_qcamotor[2653]
#define sipNameNr_sort 2658
#define sipName_sort &sipStrings_qcamotor[2658]
#define sipNameNr_stop 2231
#define sipName_stop &sipStrings_qcamotor[2231]
#define sipNameNr_jog 2663
#define sipName_jog &sipStrings_qcamotor[2663]
#define sipNameNr_get 2667
#define sipName_get &sipStrings_qcamotor[2667]
#define sipNameNr_SET 2671
#define sipName_SET &sipStrings_qcamotor[2671]
#define sipNameNr_USE 2606
#define sipName_USE &sipStrings_qcamotor[2606]
#define sipNameNr_pid 2675
#define sipName_pid &sipStrings_qcamotor[2675]
#define sipNameNr_GO 2679
#define sipName_GO &sipStrings_qcamotor[2679]

#define sipMalloc                   sipAPI_qcamotor->api_malloc
#define sipFree                     sipAPI_qcamotor->api_free
#define sipBuildResult              sipAPI_qcamotor->api_build_result
#define sipCallMethod               sipAPI_qcamotor->api_call_method
#define sipCallProcedureMethod      sipAPI_qcamotor->api_call_procedure_method
#define sipCallErrorHandler         sipAPI_qcamotor->api_call_error_handler
#define sipParseResultEx            sipAPI_qcamotor->api_parse_result_ex
#define sipParseResult              sipAPI_qcamotor->api_parse_result
#define sipParseArgs                sipAPI_qcamotor->api_parse_args
#define sipParseKwdArgs             sipAPI_qcamotor->api_parse_kwd_args
#define sipParsePair                sipAPI_qcamotor->api_parse_pair
#define sipInstanceDestroyed        sipAPI_qcamotor->api_instance_destroyed
#define sipInstanceDestroyedEx      sipAPI_qcamotor->api_instance_destroyed_ex
#define sipConvertFromSequenceIndex sipAPI_qcamotor->api_convert_from_sequence_index
#define sipConvertFromSliceObject   sipAPI_qcamotor->api_convert_from_slice_object
#define sipConvertFromVoidPtr       sipAPI_qcamotor->api_convert_from_void_ptr
#define sipConvertToVoidPtr         sipAPI_qcamotor->api_convert_to_void_ptr
#define sipAddException             sipAPI_qcamotor->api_add_exception
#define sipNoFunction               sipAPI_qcamotor->api_no_function
#define sipNoMethod                 sipAPI_qcamotor->api_no_method
#define sipAbstractMethod           sipAPI_qcamotor->api_abstract_method
#define sipBadClass                 sipAPI_qcamotor->api_bad_class
#define sipBadCatcherResult         sipAPI_qcamotor->api_bad_catcher_result
#define sipBadCallableArg           sipAPI_qcamotor->api_bad_callable_arg
#define sipBadOperatorArg           sipAPI_qcamotor->api_bad_operator_arg
#define sipTrace                    sipAPI_qcamotor->api_trace
#define sipTransferBack             sipAPI_qcamotor->api_transfer_back
#define sipTransferTo               sipAPI_qcamotor->api_transfer_to
#define sipTransferBreak            sipAPI_qcamotor->api_transfer_break
#define sipSimpleWrapper_Type       sipAPI_qcamotor->api_simplewrapper_type
#define sipWrapper_Type             sipAPI_qcamotor->api_wrapper_type
#define sipWrapperType_Type         sipAPI_qcamotor->api_wrappertype_type
#define sipVoidPtr_Type             sipAPI_qcamotor->api_voidptr_type
#define sipGetPyObject              sipAPI_qcamotor->api_get_pyobject
#define sipGetAddress               sipAPI_qcamotor->api_get_address
#define sipGetMixinAddress          sipAPI_qcamotor->api_get_mixin_address
#define sipGetCppPtr                sipAPI_qcamotor->api_get_cpp_ptr
#define sipGetComplexCppPtr         sipAPI_qcamotor->api_get_complex_cpp_ptr
#define sipIsPyMethod               sipAPI_qcamotor->api_is_py_method
#define sipCallHook                 sipAPI_qcamotor->api_call_hook
#define sipEndThread                sipAPI_qcamotor->api_end_thread
#define sipConnectRx                sipAPI_qcamotor->api_connect_rx
#define sipDisconnectRx             sipAPI_qcamotor->api_disconnect_rx
#define sipRaiseUnknownException    sipAPI_qcamotor->api_raise_unknown_exception
#define sipRaiseTypeException       sipAPI_qcamotor->api_raise_type_exception
#define sipBadLengthForSlice        sipAPI_qcamotor->api_bad_length_for_slice
#define sipAddTypeInstance          sipAPI_qcamotor->api_add_type_instance
#define sipFreeSipslot              sipAPI_qcamotor->api_free_sipslot
#define sipSameSlot                 sipAPI_qcamotor->api_same_slot
#define sipPySlotExtend             sipAPI_qcamotor->api_pyslot_extend
#define sipConvertRx                sipAPI_qcamotor->api_convert_rx
#define sipAddDelayedDtor           sipAPI_qcamotor->api_add_delayed_dtor
#define sipCanConvertToType         sipAPI_qcamotor->api_can_convert_to_type
#define sipConvertToType            sipAPI_qcamotor->api_convert_to_type
#define sipForceConvertToType       sipAPI_qcamotor->api_force_convert_to_type
#define sipCanConvertToEnum         sipAPI_qcamotor->api_can_convert_to_enum
#define sipConvertToEnum            sipAPI_qcamotor->api_convert_to_enum
#define sipConvertToBool            sipAPI_qcamotor->api_convert_to_bool
#define sipReleaseType              sipAPI_qcamotor->api_release_type
#define sipConvertFromType          sipAPI_qcamotor->api_convert_from_type
#define sipConvertFromNewType       sipAPI_qcamotor->api_convert_from_new_type
#define sipConvertFromNewPyType     sipAPI_qcamotor->api_convert_from_new_pytype
#define sipConvertFromEnum          sipAPI_qcamotor->api_convert_from_enum
#define sipGetState                 sipAPI_qcamotor->api_get_state
#define sipExportSymbol             sipAPI_qcamotor->api_export_symbol
#define sipImportSymbol             sipAPI_qcamotor->api_import_symbol
#define sipFindType                 sipAPI_qcamotor->api_find_type
#define sipFindNamedEnum            sipAPI_qcamotor->api_find_named_enum
#define sipBytes_AsChar             sipAPI_qcamotor->api_bytes_as_char
#define sipBytes_AsString           sipAPI_qcamotor->api_bytes_as_string
#define sipString_AsASCIIChar       sipAPI_qcamotor->api_string_as_ascii_char
#define sipString_AsASCIIString     sipAPI_qcamotor->api_string_as_ascii_string
#define sipString_AsLatin1Char      sipAPI_qcamotor->api_string_as_latin1_char
#define sipString_AsLatin1String    sipAPI_qcamotor->api_string_as_latin1_string
#define sipString_AsUTF8Char        sipAPI_qcamotor->api_string_as_utf8_char
#define sipString_AsUTF8String      sipAPI_qcamotor->api_string_as_utf8_string
#define sipUnicode_AsWChar          sipAPI_qcamotor->api_unicode_as_wchar
#define sipUnicode_AsWString        sipAPI_qcamotor->api_unicode_as_wstring
#define sipConvertFromConstVoidPtr  sipAPI_qcamotor->api_convert_from_const_void_ptr
#define sipConvertFromVoidPtrAndSize    sipAPI_qcamotor->api_convert_from_void_ptr_and_size
#define sipConvertFromConstVoidPtrAndSize   sipAPI_qcamotor->api_convert_from_const_void_ptr_and_size
#define sipInvokeSlot               sipAPI_qcamotor->api_invoke_slot
#define sipInvokeSlotEx             sipAPI_qcamotor->api_invoke_slot_ex
#define sipSaveSlot                 sipAPI_qcamotor->api_save_slot
#define sipClearAnySlotReference    sipAPI_qcamotor->api_clear_any_slot_reference
#define sipVisitSlot                sipAPI_qcamotor->api_visit_slot
#define sipWrappedTypeName(wt)      ((wt)->wt_td->td_cname)
#define sipDeprecated               sipAPI_qcamotor->api_deprecated
#define sipGetReference             sipAPI_qcamotor->api_get_reference
#define sipKeepReference            sipAPI_qcamotor->api_keep_reference
#define sipRegisterProxyResolver    sipAPI_qcamotor->api_register_proxy_resolver
#define sipRegisterPyType           sipAPI_qcamotor->api_register_py_type
#define sipTypeFromPyTypeObject     sipAPI_qcamotor->api_type_from_py_type_object
#define sipTypeScope                sipAPI_qcamotor->api_type_scope
#define sipResolveTypedef           sipAPI_qcamotor->api_resolve_typedef
#define sipRegisterAttributeGetter  sipAPI_qcamotor->api_register_attribute_getter
#define sipIsAPIEnabled             sipAPI_qcamotor->api_is_api_enabled
#define sipSetDestroyOnExit         sipAPI_qcamotor->api_set_destroy_on_exit
#define sipEnableAutoconversion     sipAPI_qcamotor->api_enable_autoconversion
#define sipEnableOverflowChecking   sipAPI_qcamotor->api_enable_overflow_checking
#define sipInitMixin                sipAPI_qcamotor->api_init_mixin
#define sipExportModule             sipAPI_qcamotor->api_export_module
#define sipInitModule               sipAPI_qcamotor->api_init_module
#define sipGetInterpreter           sipAPI_qcamotor->api_get_interpreter
#define sipSetNewUserTypeHandler    sipAPI_qcamotor->api_set_new_user_type_handler
#define sipSetTypeUserData          sipAPI_qcamotor->api_set_type_user_data
#define sipGetTypeUserData          sipAPI_qcamotor->api_get_type_user_data
#define sipPyTypeDict               sipAPI_qcamotor->api_py_type_dict
#define sipPyTypeName               sipAPI_qcamotor->api_py_type_name
#define sipGetCFunction             sipAPI_qcamotor->api_get_c_function
#define sipGetMethod                sipAPI_qcamotor->api_get_method
#define sipFromMethod               sipAPI_qcamotor->api_from_method
#define sipGetDate                  sipAPI_qcamotor->api_get_date
#define sipFromDate                 sipAPI_qcamotor->api_from_date
#define sipGetDateTime              sipAPI_qcamotor->api_get_datetime
#define sipFromDateTime             sipAPI_qcamotor->api_from_datetime
#define sipGetTime                  sipAPI_qcamotor->api_get_time
#define sipFromTime                 sipAPI_qcamotor->api_from_time
#define sipIsUserType               sipAPI_qcamotor->api_is_user_type
#define sipGetFrame                 sipAPI_qcamotor->api_get_frame
#define sipCheckPluginForType       sipAPI_qcamotor->api_check_plugin_for_type
#define sipUnicodeNew               sipAPI_qcamotor->api_unicode_new
#define sipUnicodeWrite             sipAPI_qcamotor->api_unicode_write
#define sipUnicodeData              sipAPI_qcamotor->api_unicode_data
#define sipGetBufferInfo            sipAPI_qcamotor->api_get_buffer_info
#define sipReleaseBufferInfo        sipAPI_qcamotor->api_release_buffer_info
#define sipIsOwnedByPython          sipAPI_qcamotor->api_is_owned_by_python
#define sipIsDerivedClass           sipAPI_qcamotor->api_is_derived_class
#define sipGetUserObject            sipAPI_qcamotor->api_get_user_object
#define sipSetUserObject            sipAPI_qcamotor->api_set_user_object
#define sipRegisterEventHandler     sipAPI_qcamotor->api_register_event_handler
#define sipLong_AsChar              sipAPI_qcamotor->api_long_as_char
#define sipLong_AsSignedChar        sipAPI_qcamotor->api_long_as_signed_char
#define sipLong_AsUnsignedChar      sipAPI_qcamotor->api_long_as_unsigned_char
#define sipLong_AsShort             sipAPI_qcamotor->api_long_as_short
#define sipLong_AsUnsignedShort     sipAPI_qcamotor->api_long_as_unsigned_short
#define sipLong_AsInt               sipAPI_qcamotor->api_long_as_int
#define sipLong_AsUnsignedInt       sipAPI_qcamotor->api_long_as_unsigned_int
#define sipLong_AsLong              sipAPI_qcamotor->api_long_as_long
#define sipLong_AsUnsignedLong      sipAPI_qcamotor->api_long_as_unsigned_long
#define sipLong_AsLongLong          sipAPI_qcamotor->api_long_as_long_long
#define sipLong_AsUnsignedLongLong  sipAPI_qcamotor->api_long_as_unsigned_long_long

/* These are deprecated. */
#define sipMapStringToClass         sipAPI_qcamotor->api_map_string_to_class
#define sipMapIntToClass            sipAPI_qcamotor->api_map_int_to_class
#define sipFindClass                sipAPI_qcamotor->api_find_class
#define sipFindMappedType           sipAPI_qcamotor->api_find_mapped_type
#define sipConvertToArray           sipAPI_qcamotor->api_convert_to_array
#define sipConvertToTypedArray      sipAPI_qcamotor->api_convert_to_typed_array
#define sipEnableGC                 sipAPI_qcamotor->api_enable_gc
#define sipPrintObject              sipAPI_qcamotor->api_print_object
#define sipWrapper_Check(w)         PyObject_TypeCheck((w), sipAPI_qcamotor->api_wrapper_type)
#define sipGetWrapper(p, wt)        sipGetPyObject((p), (wt)->wt_td)
#define sipReleaseInstance(p, wt, s)    sipReleaseType((p), (wt)->wt_td, (s))
#define sipReleaseMappedType        sipReleaseType
#define sipCanConvertToInstance(o, wt, f)   sipCanConvertToType((o), (wt)->wt_td, (f))
#define sipCanConvertToMappedType   sipCanConvertToType
#define sipConvertToInstance(o, wt, t, f, s, e)     sipConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipConvertToMappedType      sipConvertToType
#define sipForceConvertToInstance(o, wt, t, f, s, e)    sipForceConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipForceConvertToMappedType sipForceConvertToType
#define sipConvertFromInstance(p, wt, t)    sipConvertFromType((p), (wt)->wt_td, (t))
#define sipConvertFromMappedType    sipConvertFromType
#define sipConvertFromNamedEnum(v, pt)  sipConvertFromEnum((v), ((sipEnumTypeObject *)(pt))->type)
#define sipConvertFromNewInstance(p, wt, t) sipConvertFromNewType((p), (wt)->wt_td, (t))

/* The strings used by this module. */
extern const char sipStrings_qcamotor[];

#define sipType_QCaMotor sipExportedTypes_qcamotor[0]
#define sipClass_QCaMotor sipExportedTypes_qcamotor[0]->u.td_wrapper_type

#define sipType_QCaMotor_MotionExit sipExportedTypes_qcamotor[2]
#define sipEnum_QCaMotor_MotionExit sipExportedTypes_qcamotor[2]->u.td_py_type

#define sipType_QCaMotor_Direction sipExportedTypes_qcamotor[1]
#define sipEnum_QCaMotor_Direction sipExportedTypes_qcamotor[1]->u.td_py_type

#define sipType_QCaMotor_OffMode sipExportedTypes_qcamotor[3]
#define sipEnum_QCaMotor_OffMode sipExportedTypes_qcamotor[3]->u.td_py_type

#define sipType_QCaMotor_SuMode sipExportedTypes_qcamotor[5]
#define sipEnum_QCaMotor_SuMode sipExportedTypes_qcamotor[5]->u.td_py_type

#define sipType_QCaMotor_SpmgMode sipExportedTypes_qcamotor[4]
#define sipEnum_QCaMotor_SpmgMode sipExportedTypes_qcamotor[4]->u.td_py_type

extern sipClassTypeDef sipTypeDef_qcamotor_QCaMotor;

/* The SIP API, this module's API and the APIs of any imported modules. */
extern const sipAPIDef *sipAPI_qcamotor;
extern sipExportedModuleDef sipModuleAPI_qcamotor;
extern sipTypeDef *sipExportedTypes_qcamotor[];

#define sipType_QObject sipImportedTypes_qcamotor_QtCore[3].it_td
#define sipClass_QObject sipImportedTypes_qcamotor_QtCore[3].it_td->u.td_wrapper_type

#define sipType_QEvent sipImportedTypes_qcamotor_QtCore[1].it_td
#define sipClass_QEvent sipImportedTypes_qcamotor_QtCore[1].it_td->u.td_wrapper_type

#define sipType_QTimerEvent sipImportedTypes_qcamotor_QtCore[5].it_td
#define sipClass_QTimerEvent sipImportedTypes_qcamotor_QtCore[5].it_td->u.td_wrapper_type

#define sipType_QChildEvent sipImportedTypes_qcamotor_QtCore[0].it_td
#define sipClass_QChildEvent sipImportedTypes_qcamotor_QtCore[0].it_td->u.td_wrapper_type

#define sipType_QMetaMethod sipImportedTypes_qcamotor_QtCore[2].it_td
#define sipClass_QMetaMethod sipImportedTypes_qcamotor_QtCore[2].it_td->u.td_wrapper_type

#define sipType_QString sipImportedTypes_qcamotor_QtCore[4].it_td
extern sipImportedTypeDef sipImportedTypes_qcamotor_QtCore[];
extern sipImportedVirtErrorHandlerDef sipImportedVirtErrorHandlers_qcamotor_QtCore[];

typedef const QMetaObject *(*sip_qt_metaobject_func)(sipSimpleWrapper *,sipTypeDef *);
extern sip_qt_metaobject_func sip_qcamotor_qt_metaobject;

typedef int (*sip_qt_metacall_func)(sipSimpleWrapper *,sipTypeDef *,QMetaObject::Call,int,void **);
extern sip_qt_metacall_func sip_qcamotor_qt_metacall;

typedef bool (*sip_qt_metacast_func)(sipSimpleWrapper *, const sipTypeDef *, const char *, void **);
extern sip_qt_metacast_func sip_qcamotor_qt_metacast;

#endif
