/*
 * Internal module API header file.
 *
 * Generated by SIP 4.19.16
 */

#ifndef _pyqcamotorAPI_H
#define _pyqcamotorAPI_H

#include <sip.h>

#include <QMetaType>
#include <QThread>

/* These are the qualifiers that are enabled. */
#define SIP_FEATURE_PyQt_MacOSXOnly
#define SIP_FEATURE_PyQt_Process
#define SIP_FEATURE_PyQt_NotBootstrapped
#define SIP_FEATURE_PyQt_Desktop_OpenGL
#define SIP_FEATURE_PyQt_OpenGL
#define SIP_FEATURE_PyQt_RawFont
#define SIP_FEATURE_PyQt_PrintPreviewDialog
#define SIP_FEATURE_PyQt_PrintPreviewWidget
#define SIP_FEATURE_PyQt_Printer
#define SIP_FEATURE_PyQt_PrintDialog
#define SIP_FEATURE_Py_v3
#define SIP_FEATURE_PyQt_qreal_double
#define SIP_FEATURE_PyQt_SSL
#define SIP_FEATURE_PyQt_SessionManager
#define SIP_FEATURE_PyQt_Accessibility
#define SIP_PLATFORM_WS_X11


/*
 * Convenient names to refer to various strings defined in this module.
 * Only the class names are part of the public API.
 */
#define sipNameNr_changedBacklashAcceleration 0
#define sipName_changedBacklashAcceleration &sipStrings_pyqcamotor[0]
#define sipNameNr_changedReadbackResolution 28
#define sipName_changedReadbackResolution &sipStrings_pyqcamotor[28]
#define sipNameNr_changedEncoderResolution 54
#define sipName_changedEncoderResolution &sipStrings_pyqcamotor[54]
#define sipNameNr_setBacklashAcceleration 79
#define sipName_setBacklashAcceleration &sipStrings_pyqcamotor[79]
#define sipNameNr_getBacklashAcceleration 103
#define sipName_getBacklashAcceleration &sipStrings_pyqcamotor[103]
#define sipNameNr_changedPowerConnection 127
#define sipName_changedPowerConnection &sipStrings_pyqcamotor[127]
#define sipNameNr_changedJogAcceleration 150
#define sipName_changedJogAcceleration &sipStrings_pyqcamotor[150]
#define sipNameNr_changedMotorResolution 173
#define sipName_changedMotorResolution &sipStrings_pyqcamotor[173]
#define sipNameNr_setReadbackResolution 196
#define sipName_setReadbackResolution &sipStrings_pyqcamotor[196]
#define sipNameNr_getReadbackResolution 218
#define sipName_getReadbackResolution &sipStrings_pyqcamotor[218]
#define sipNameNr_changedBacklashSpeed 240
#define sipName_changedBacklashSpeed &sipStrings_pyqcamotor[240]
#define sipNameNr_changedLoLimitStatus 261
#define sipName_changedLoLimitStatus &sipStrings_pyqcamotor[261]
#define sipNameNr_changedHiLimitStatus 282
#define sipName_changedHiLimitStatus &sipStrings_pyqcamotor[282]
#define sipNameNr_setEncoderResolution 303
#define sipName_setEncoderResolution &sipStrings_pyqcamotor[303]
#define sipNameNr_getEncoderResolution 324
#define sipName_getEncoderResolution &sipStrings_pyqcamotor[324]
#define sipNameNr_QCaMotor__MotionExit 345
#define sipName_QCaMotor__MotionExit &sipStrings_pyqcamotor[345]
#define sipNameNr_changedAcceleration 366
#define sipName_changedAcceleration &sipStrings_pyqcamotor[366]
#define sipNameNr_changedMaximumSpeed 386
#define sipName_changedMaximumSpeed &sipStrings_pyqcamotor[386]
#define sipNameNr_changedDialPosition 406
#define sipName_changedDialPosition &sipStrings_pyqcamotor[406]
#define sipNameNr_changedUserPosition 426
#define sipName_changedUserPosition &sipStrings_pyqcamotor[426]
#define sipNameNr_QCaMotor__Direction 446
#define sipName_QCaMotor__Direction &sipStrings_pyqcamotor[446]
#define sipNameNr_changedUseReadback 466
#define sipName_changedUseReadback &sipStrings_pyqcamotor[466]
#define sipNameNr_changedNormalSpeed 485
#define sipName_changedNormalSpeed &sipStrings_pyqcamotor[485]
#define sipNameNr_changedStepsPerRev 504
#define sipName_changedStepsPerRev &sipStrings_pyqcamotor[504]
#define sipNameNr_changedUnitsPerRev 523
#define sipName_changedUnitsPerRev &sipStrings_pyqcamotor[523]
#define sipNameNr_changedDialHiLimit 542
#define sipName_changedDialHiLimit &sipStrings_pyqcamotor[542]
#define sipNameNr_changedDialLoLimit 561
#define sipName_changedDialLoLimit &sipStrings_pyqcamotor[561]
#define sipNameNr_changedUserLoLimit 580
#define sipName_changedUserLoLimit &sipStrings_pyqcamotor[580]
#define sipNameNr_changedUserHiLimit 599
#define sipName_changedUserHiLimit &sipStrings_pyqcamotor[599]
#define sipNameNr_changedRawPosition 618
#define sipName_changedRawPosition &sipStrings_pyqcamotor[618]
#define sipNameNr_changedDescription 637
#define sipName_changedDescription &sipStrings_pyqcamotor[637]
#define sipNameNr_setJogAcceleration 656
#define sipName_setJogAcceleration &sipStrings_pyqcamotor[656]
#define sipNameNr_setMotorResolution 675
#define sipName_setMotorResolution &sipStrings_pyqcamotor[675]
#define sipNameNr_getPowerConnection 694
#define sipName_getPowerConnection &sipStrings_pyqcamotor[694]
#define sipNameNr_getJogAcceleration 713
#define sipName_getJogAcceleration &sipStrings_pyqcamotor[713]
#define sipNameNr_getMotorResolution 732
#define sipName_getMotorResolution &sipStrings_pyqcamotor[732]
#define sipNameNr_QCaMotor__SpmgMode 751
#define sipName_QCaMotor__SpmgMode &sipStrings_pyqcamotor[751]
#define sipNameNr_changedUseEncoder 770
#define sipName_changedUseEncoder &sipStrings_pyqcamotor[770]
#define sipNameNr_changedOffsetMode 788
#define sipName_changedOffsetMode &sipStrings_pyqcamotor[788]
#define sipNameNr_loadConfiguration 806
#define sipName_loadConfiguration &sipStrings_pyqcamotor[806]
#define sipNameNr_saveConfiguration 824
#define sipName_saveConfiguration &sipStrings_pyqcamotor[824]
#define sipNameNr_QCaMotor__OffMode 842
#define sipName_QCaMotor__OffMode &sipStrings_pyqcamotor[842]
#define sipNameNr_isSignalConnected 860
#define sipName_isSignalConnected &sipStrings_pyqcamotor[860]
#define sipNameNr_senderSignalIndex 878
#define sipName_senderSignalIndex &sipStrings_pyqcamotor[878]
#define sipNameNr_changedConnected 896
#define sipName_changedConnected &sipStrings_pyqcamotor[896]
#define sipNameNr_changedDirection 913
#define sipName_changedDirection &sipStrings_pyqcamotor[913]
#define sipNameNr_changedPrecision 930
#define sipName_changedPrecision &sipStrings_pyqcamotor[930]
#define sipNameNr_setBacklashSpeed 947
#define sipName_setBacklashSpeed &sipStrings_pyqcamotor[947]
#define sipNameNr_getBacklashSpeed 964
#define sipName_getBacklashSpeed &sipStrings_pyqcamotor[964]
#define sipNameNr_getLoLimitStatus 981
#define sipName_getLoLimitStatus &sipStrings_pyqcamotor[981]
#define sipNameNr_getHiLimitStatus 998
#define sipName_getHiLimitStatus &sipStrings_pyqcamotor[998]
#define sipNameNr_QCaMotor__SuMode 1015
#define sipName_QCaMotor__SuMode &sipStrings_pyqcamotor[1015]
#define sipNameNr_disconnectNotify 1032
#define sipName_disconnectNotify &sipStrings_pyqcamotor[1032]
#define sipNameNr_changedSpmgMode 1049
#define sipName_changedSpmgMode &sipStrings_pyqcamotor[1049]
#define sipNameNr_changedBacklash 1065
#define sipName_changedBacklash &sipStrings_pyqcamotor[1065]
#define sipNameNr_changedJogSpeed 1081
#define sipName_changedJogSpeed &sipStrings_pyqcamotor[1081]
#define sipNameNr_changedRevSpeed 1097
#define sipName_changedRevSpeed &sipStrings_pyqcamotor[1097]
#define sipNameNr_changedDeadBand 1113
#define sipName_changedDeadBand &sipStrings_pyqcamotor[1113]
#define sipNameNr_changedDialGoal 1129
#define sipName_changedDialGoal &sipStrings_pyqcamotor[1129]
#define sipNameNr_changedUserGoal 1145
#define sipName_changedUserGoal &sipStrings_pyqcamotor[1145]
#define sipNameNr_setAcceleration 1161
#define sipName_setAcceleration &sipStrings_pyqcamotor[1161]
#define sipNameNr_setMaximumSpeed 1177
#define sipName_setMaximumSpeed &sipStrings_pyqcamotor[1177]
#define sipNameNr_setDialPosition 1193
#define sipName_setDialPosition &sipStrings_pyqcamotor[1193]
#define sipNameNr_setUserPosition 1209
#define sipName_setUserPosition &sipStrings_pyqcamotor[1209]
#define sipNameNr_getAcceleration 1225
#define sipName_getAcceleration &sipStrings_pyqcamotor[1225]
#define sipNameNr_getMaximumSpeed 1241
#define sipName_getMaximumSpeed &sipStrings_pyqcamotor[1241]
#define sipNameNr_getDialPosition 1257
#define sipName_getDialPosition &sipStrings_pyqcamotor[1257]
#define sipNameNr_getUserPosition 1273
#define sipName_getUserPosition &sipStrings_pyqcamotor[1273]
#define sipNameNr_changedRawGoal 1289
#define sipName_changedRawGoal &sipStrings_pyqcamotor[1289]
#define sipNameNr_setUseReadback 1304
#define sipName_setUseReadback &sipStrings_pyqcamotor[1304]
#define sipNameNr_setNormalSpeed 1319
#define sipName_setNormalSpeed &sipStrings_pyqcamotor[1319]
#define sipNameNr_setStepsPerRev 1334
#define sipName_setStepsPerRev &sipStrings_pyqcamotor[1334]
#define sipNameNr_setUnitsPerRev 1349
#define sipName_setUnitsPerRev &sipStrings_pyqcamotor[1349]
#define sipNameNr_setDialLoLimit 1364
#define sipName_setDialLoLimit &sipStrings_pyqcamotor[1364]
#define sipNameNr_setDialHiLimit 1379
#define sipName_setDialHiLimit &sipStrings_pyqcamotor[1379]
#define sipNameNr_setUserLoLimit 1394
#define sipName_setUserLoLimit &sipStrings_pyqcamotor[1394]
#define sipNameNr_setUserHiLimit 1409
#define sipName_setUserHiLimit &sipStrings_pyqcamotor[1409]
#define sipNameNr_undoLastMotion 1424
#define sipName_undoLastMotion &sipStrings_pyqcamotor[1424]
#define sipNameNr_goDialPosition 1439
#define sipName_goDialPosition &sipStrings_pyqcamotor[1439]
#define sipNameNr_goUserPosition 1454
#define sipName_goUserPosition &sipStrings_pyqcamotor[1454]
#define sipNameNr_setRawPosition 1469
#define sipName_setRawPosition &sipStrings_pyqcamotor[1469]
#define sipNameNr_getUseReadback 1484
#define sipName_getUseReadback &sipStrings_pyqcamotor[1484]
#define sipNameNr_getNormalSpeed 1499
#define sipName_getNormalSpeed &sipStrings_pyqcamotor[1499]
#define sipNameNr_getStepsPerRev 1514
#define sipName_getStepsPerRev &sipStrings_pyqcamotor[1514]
#define sipNameNr_getUnitsPerRev 1529
#define sipName_getUnitsPerRev &sipStrings_pyqcamotor[1529]
#define sipNameNr_getDialHiLimit 1544
#define sipName_getDialHiLimit &sipStrings_pyqcamotor[1544]
#define sipNameNr_getDialLoLimit 1559
#define sipName_getDialLoLimit &sipStrings_pyqcamotor[1559]
#define sipNameNr_getUserLoLimit 1574
#define sipName_getUserLoLimit &sipStrings_pyqcamotor[1574]
#define sipNameNr_getUserHiLimit 1589
#define sipName_getUserHiLimit &sipStrings_pyqcamotor[1589]
#define sipNameNr_getLimitStatus 1604
#define sipName_getLimitStatus &sipStrings_pyqcamotor[1604]
#define sipNameNr_getRawPosition 1619
#define sipName_getRawPosition &sipStrings_pyqcamotor[1619]
#define sipNameNr_getDescription 1634
#define sipName_getDescription &sipStrings_pyqcamotor[1634]
#define sipNameNr_setDescription 1649
#define sipName_setDescription &sipStrings_pyqcamotor[1649]
#define sipNameNr_changedMoving 1664
#define sipName_changedMoving &sipStrings_pyqcamotor[1664]
#define sipNameNr_changedSuMode 1678
#define sipName_changedSuMode &sipStrings_pyqcamotor[1678]
#define sipNameNr_changedOffset 1692
#define sipName_changedOffset &sipStrings_pyqcamotor[1692]
#define sipNameNr_setUseEncoder 1706
#define sipName_setUseEncoder &sipStrings_pyqcamotor[1706]
#define sipNameNr_setOffsetMode 1720
#define sipName_setOffsetMode &sipStrings_pyqcamotor[1720]
#define sipNameNr_goRawPosition 1734
#define sipName_goRawPosition &sipStrings_pyqcamotor[1734]
#define sipNameNr_getUseEncoder 1748
#define sipName_getUseEncoder &sipStrings_pyqcamotor[1748]
#define sipNameNr_getOffsetMode 1762
#define sipName_getOffsetMode &sipStrings_pyqcamotor[1762]
#define sipNameNr_getLastMotion 1776
#define sipName_getLastMotion &sipStrings_pyqcamotor[1776]
#define sipNameNr_connectNotify 1035
#define sipName_connectNotify &sipStrings_pyqcamotor[1035]
#define sipNameNr_changedWired 1790
#define sipName_changedWired &sipStrings_pyqcamotor[1790]
#define sipNameNr_changedPower 1803
#define sipName_changedPower &sipStrings_pyqcamotor[1803]
#define sipNameNr_changedUnits 1816
#define sipName_changedUnits &sipStrings_pyqcamotor[1816]
#define sipNameNr_setPrecision 1829
#define sipName_setPrecision &sipStrings_pyqcamotor[1829]
#define sipNameNr_getDirection 1842
#define sipName_getDirection &sipStrings_pyqcamotor[1842]
#define sipNameNr_getPrecision 1855
#define sipName_getPrecision &sipStrings_pyqcamotor[1855]
#define sipNameNr_CONFIRMATION 1868
#define sipName_CONFIRMATION &sipStrings_pyqcamotor[1868]
#define sipNameNr_setDirection 1881
#define sipName_setDirection &sipStrings_pyqcamotor[1881]
#define sipNameNr_changedStep 1894
#define sipName_changedStep &sipStrings_pyqcamotor[1894]
#define sipNameNr_setSpmgMode 1906
#define sipName_setSpmgMode &sipStrings_pyqcamotor[1906]
#define sipNameNr_setBacklash 1918
#define sipName_setBacklash &sipStrings_pyqcamotor[1918]
#define sipNameNr_setJogSpeed 1930
#define sipName_setJogSpeed &sipStrings_pyqcamotor[1930]
#define sipNameNr_setRevSpeed 1942
#define sipName_setRevSpeed &sipStrings_pyqcamotor[1942]
#define sipNameNr_setDeadBand 1954
#define sipName_setDeadBand &sipStrings_pyqcamotor[1954]
#define sipNameNr_getSpmgMode 1966
#define sipName_getSpmgMode &sipStrings_pyqcamotor[1966]
#define sipNameNr_getBacklash 1978
#define sipName_getBacklash &sipStrings_pyqcamotor[1978]
#define sipNameNr_isConnected 1990
#define sipName_isConnected &sipStrings_pyqcamotor[1990]
#define sipNameNr_getJogSpeed 2002
#define sipName_getJogSpeed &sipStrings_pyqcamotor[2002]
#define sipNameNr_getRevSpeed 2014
#define sipName_getRevSpeed &sipStrings_pyqcamotor[2014]
#define sipNameNr_getDeadBand 2026
#define sipName_getDeadBand &sipStrings_pyqcamotor[2026]
#define sipNameNr_getDialGoal 2038
#define sipName_getDialGoal &sipStrings_pyqcamotor[2038]
#define sipNameNr_getUserGoal 2050
#define sipName_getUserGoal &sipStrings_pyqcamotor[2050]
#define sipNameNr_ACCELERATED 2062
#define sipName_ACCELERATED &sipStrings_pyqcamotor[2062]
#define sipNameNr_IMMIDIATELY 2074
#define sipName_IMMIDIATELY &sipStrings_pyqcamotor[2074]
#define sipNameNr_customEvent 2086
#define sipName_customEvent &sipStrings_pyqcamotor[2086]
#define sipNameNr_eventFilter 2098
#define sipName_eventFilter &sipStrings_pyqcamotor[2098]
#define sipNameNr_printError 2110
#define sipName_printError &sipStrings_pyqcamotor[2110]
#define sipNameNr_goRelative 2121
#define sipName_goRelative &sipStrings_pyqcamotor[2121]
#define sipNameNr_getRawGoal 2132
#define sipName_getRawGoal &sipStrings_pyqcamotor[2132]
#define sipNameNr_wait_start 2143
#define sipName_wait_start &sipStrings_pyqcamotor[2143]
#define sipNameNr_MotionExit 355
#define sipName_MotionExit &sipStrings_pyqcamotor[355]
#define sipNameNr_childEvent 2154
#define sipName_childEvent &sipStrings_pyqcamotor[2154]
#define sipNameNr_timerEvent 2165
#define sipName_timerEvent &sipStrings_pyqcamotor[2165]
#define sipNameNr_pyqcamotor 2176
#define sipName_pyqcamotor &sipStrings_pyqcamotor[2176]
#define sipNameNr_changedPv 2187
#define sipName_changedPv &sipStrings_pyqcamotor[2187]
#define sipNameNr_setSuMode 2197
#define sipName_setSuMode &sipStrings_pyqcamotor[2197]
#define sipNameNr_setOffset 2207
#define sipName_setOffset &sipStrings_pyqcamotor[2207]
#define sipNameNr_getSuMode 2217
#define sipName_getSuMode &sipStrings_pyqcamotor[2217]
#define sipNameNr_getOffset 2227
#define sipName_getOffset &sipStrings_pyqcamotor[2227]
#define sipNameNr_wait_stop 2237
#define sipName_wait_stop &sipStrings_pyqcamotor[2237]
#define sipNameNr_receivers 2247
#define sipName_receivers &sipStrings_pyqcamotor[2247]
#define sipNameNr_Direction 456
#define sipName_Direction &sipStrings_pyqcamotor[456]
#define sipNameNr_setPower 2257
#define sipName_setPower &sipStrings_pyqcamotor[2257]
#define sipNameNr_setUnits 2266
#define sipName_setUnits &sipStrings_pyqcamotor[2266]
#define sipNameNr_getPower 2275
#define sipName_getPower &sipStrings_pyqcamotor[2275]
#define sipNameNr_isMoving 2284
#define sipName_isMoving &sipStrings_pyqcamotor[2284]
#define sipNameNr_getUnits 2293
#define sipName_getUnits &sipStrings_pyqcamotor[2293]
#define sipNameNr_NEGATIVE 2302
#define sipName_NEGATIVE &sipStrings_pyqcamotor[2302]
#define sipNameNr_POSITIVE 2311
#define sipName_POSITIVE &sipStrings_pyqcamotor[2311]
#define sipNameNr_VARIABLE 2320
#define sipName_VARIABLE &sipStrings_pyqcamotor[2320]
#define sipNameNr_SpmgMode 761
#define sipName_SpmgMode &sipStrings_pyqcamotor[761]
#define sipNameNr_QCaMotor 2329
#define sipName_QCaMotor &sipStrings_pyqcamotor[2329]
#define sipNameNr_setStep 2338
#define sipName_setStep &sipStrings_pyqcamotor[2338]
#define sipNameNr_goLimit 2346
#define sipName_goLimit &sipStrings_pyqcamotor[2346]
#define sipNameNr_isWired 2354
#define sipName_isWired &sipStrings_pyqcamotor[2354]
#define sipNameNr_getStep 2362
#define sipName_getStep &sipStrings_pyqcamotor[2362]
#define sipNameNr_STOPPED 2370
#define sipName_STOPPED &sipStrings_pyqcamotor[2370]
#define sipNameNr_STARTED 2378
#define sipName_STARTED &sipStrings_pyqcamotor[2378]
#define sipNameNr_OffMode 852
#define sipName_OffMode &sipStrings_pyqcamotor[852]
#define sipNameNr_stopped 2386
#define sipName_stopped &sipStrings_pyqcamotor[2386]
#define sipNameNr_enabled 2394
#define sipName_enabled &sipStrings_pyqcamotor[2394]
#define sipNameNr_goHome 2402
#define sipName_goHome &sipStrings_pyqcamotor[2402]
#define sipNameNr_goStep 2409
#define sipName_goStep &sipStrings_pyqcamotor[2409]
#define sipNameNr_FROZEN 2416
#define sipName_FROZEN &sipStrings_pyqcamotor[2416]
#define sipNameNr_SuMode 1025
#define sipName_SuMode &sipStrings_pyqcamotor[1025]
#define sipNameNr_sender 2423
#define sipName_sender &sipStrings_pyqcamotor[2423]
#define sipNameNr_object 2430
#define sipName_object &sipStrings_pyqcamotor[2430]
#define sipNameNr_setPv 2437
#define sipName_setPv &sipStrings_pyqcamotor[2437]
#define sipNameNr_getPv 2443
#define sipName_getPv &sipStrings_pyqcamotor[2443]
#define sipNameNr_PAUSE 2449
#define sipName_PAUSE &sipStrings_pyqcamotor[2449]
#define sipNameNr_error 2455
#define sipName_error &sipStrings_pyqcamotor[2455]
#define sipNameNr_event 2461
#define sipName_event &sipStrings_pyqcamotor[2461]
#define sipNameNr_MOVE 2467
#define sipName_MOVE &sipStrings_pyqcamotor[2467]
#define sipNameNr_STOP 2472
#define sipName_STOP &sipStrings_pyqcamotor[2472]
#define sipNameNr_stop 2242
#define sipName_stop &sipStrings_pyqcamotor[2242]
#define sipNameNr_jog 2477
#define sipName_jog &sipStrings_pyqcamotor[2477]
#define sipNameNr_get 2481
#define sipName_get &sipStrings_pyqcamotor[2481]
#define sipNameNr_SET 2485
#define sipName_SET &sipStrings_pyqcamotor[2485]
#define sipNameNr_USE 2451
#define sipName_USE &sipStrings_pyqcamotor[2451]
#define sipNameNr_GO 2489
#define sipName_GO &sipStrings_pyqcamotor[2489]

#define sipMalloc                   sipAPI_pyqcamotor->api_malloc
#define sipFree                     sipAPI_pyqcamotor->api_free
#define sipBuildResult              sipAPI_pyqcamotor->api_build_result
#define sipCallMethod               sipAPI_pyqcamotor->api_call_method
#define sipCallProcedureMethod      sipAPI_pyqcamotor->api_call_procedure_method
#define sipCallErrorHandler         sipAPI_pyqcamotor->api_call_error_handler
#define sipParseResultEx            sipAPI_pyqcamotor->api_parse_result_ex
#define sipParseResult              sipAPI_pyqcamotor->api_parse_result
#define sipParseArgs                sipAPI_pyqcamotor->api_parse_args
#define sipParseKwdArgs             sipAPI_pyqcamotor->api_parse_kwd_args
#define sipParsePair                sipAPI_pyqcamotor->api_parse_pair
#define sipInstanceDestroyed        sipAPI_pyqcamotor->api_instance_destroyed
#define sipInstanceDestroyedEx      sipAPI_pyqcamotor->api_instance_destroyed_ex
#define sipConvertFromSequenceIndex sipAPI_pyqcamotor->api_convert_from_sequence_index
#define sipConvertFromSliceObject   sipAPI_pyqcamotor->api_convert_from_slice_object
#define sipConvertFromVoidPtr       sipAPI_pyqcamotor->api_convert_from_void_ptr
#define sipConvertToVoidPtr         sipAPI_pyqcamotor->api_convert_to_void_ptr
#define sipAddException             sipAPI_pyqcamotor->api_add_exception
#define sipNoFunction               sipAPI_pyqcamotor->api_no_function
#define sipNoMethod                 sipAPI_pyqcamotor->api_no_method
#define sipAbstractMethod           sipAPI_pyqcamotor->api_abstract_method
#define sipBadClass                 sipAPI_pyqcamotor->api_bad_class
#define sipBadCatcherResult         sipAPI_pyqcamotor->api_bad_catcher_result
#define sipBadCallableArg           sipAPI_pyqcamotor->api_bad_callable_arg
#define sipBadOperatorArg           sipAPI_pyqcamotor->api_bad_operator_arg
#define sipTrace                    sipAPI_pyqcamotor->api_trace
#define sipTransferBack             sipAPI_pyqcamotor->api_transfer_back
#define sipTransferTo               sipAPI_pyqcamotor->api_transfer_to
#define sipTransferBreak            sipAPI_pyqcamotor->api_transfer_break
#define sipSimpleWrapper_Type       sipAPI_pyqcamotor->api_simplewrapper_type
#define sipWrapper_Type             sipAPI_pyqcamotor->api_wrapper_type
#define sipWrapperType_Type         sipAPI_pyqcamotor->api_wrappertype_type
#define sipVoidPtr_Type             sipAPI_pyqcamotor->api_voidptr_type
#define sipGetPyObject              sipAPI_pyqcamotor->api_get_pyobject
#define sipGetAddress               sipAPI_pyqcamotor->api_get_address
#define sipGetMixinAddress          sipAPI_pyqcamotor->api_get_mixin_address
#define sipGetCppPtr                sipAPI_pyqcamotor->api_get_cpp_ptr
#define sipGetComplexCppPtr         sipAPI_pyqcamotor->api_get_complex_cpp_ptr
#define sipIsPyMethod               sipAPI_pyqcamotor->api_is_py_method
#define sipCallHook                 sipAPI_pyqcamotor->api_call_hook
#define sipEndThread                sipAPI_pyqcamotor->api_end_thread
#define sipConnectRx                sipAPI_pyqcamotor->api_connect_rx
#define sipDisconnectRx             sipAPI_pyqcamotor->api_disconnect_rx
#define sipRaiseUnknownException    sipAPI_pyqcamotor->api_raise_unknown_exception
#define sipRaiseTypeException       sipAPI_pyqcamotor->api_raise_type_exception
#define sipBadLengthForSlice        sipAPI_pyqcamotor->api_bad_length_for_slice
#define sipAddTypeInstance          sipAPI_pyqcamotor->api_add_type_instance
#define sipFreeSipslot              sipAPI_pyqcamotor->api_free_sipslot
#define sipSameSlot                 sipAPI_pyqcamotor->api_same_slot
#define sipPySlotExtend             sipAPI_pyqcamotor->api_pyslot_extend
#define sipConvertRx                sipAPI_pyqcamotor->api_convert_rx
#define sipAddDelayedDtor           sipAPI_pyqcamotor->api_add_delayed_dtor
#define sipCanConvertToType         sipAPI_pyqcamotor->api_can_convert_to_type
#define sipConvertToType            sipAPI_pyqcamotor->api_convert_to_type
#define sipForceConvertToType       sipAPI_pyqcamotor->api_force_convert_to_type
#define sipCanConvertToEnum         sipAPI_pyqcamotor->api_can_convert_to_enum
#define sipConvertToEnum            sipAPI_pyqcamotor->api_convert_to_enum
#define sipConvertToBool            sipAPI_pyqcamotor->api_convert_to_bool
#define sipReleaseType              sipAPI_pyqcamotor->api_release_type
#define sipConvertFromType          sipAPI_pyqcamotor->api_convert_from_type
#define sipConvertFromNewType       sipAPI_pyqcamotor->api_convert_from_new_type
#define sipConvertFromNewPyType     sipAPI_pyqcamotor->api_convert_from_new_pytype
#define sipConvertFromEnum          sipAPI_pyqcamotor->api_convert_from_enum
#define sipGetState                 sipAPI_pyqcamotor->api_get_state
#define sipExportSymbol             sipAPI_pyqcamotor->api_export_symbol
#define sipImportSymbol             sipAPI_pyqcamotor->api_import_symbol
#define sipFindType                 sipAPI_pyqcamotor->api_find_type
#define sipFindNamedEnum            sipAPI_pyqcamotor->api_find_named_enum
#define sipBytes_AsChar             sipAPI_pyqcamotor->api_bytes_as_char
#define sipBytes_AsString           sipAPI_pyqcamotor->api_bytes_as_string
#define sipString_AsASCIIChar       sipAPI_pyqcamotor->api_string_as_ascii_char
#define sipString_AsASCIIString     sipAPI_pyqcamotor->api_string_as_ascii_string
#define sipString_AsLatin1Char      sipAPI_pyqcamotor->api_string_as_latin1_char
#define sipString_AsLatin1String    sipAPI_pyqcamotor->api_string_as_latin1_string
#define sipString_AsUTF8Char        sipAPI_pyqcamotor->api_string_as_utf8_char
#define sipString_AsUTF8String      sipAPI_pyqcamotor->api_string_as_utf8_string
#define sipUnicode_AsWChar          sipAPI_pyqcamotor->api_unicode_as_wchar
#define sipUnicode_AsWString        sipAPI_pyqcamotor->api_unicode_as_wstring
#define sipConvertFromConstVoidPtr  sipAPI_pyqcamotor->api_convert_from_const_void_ptr
#define sipConvertFromVoidPtrAndSize    sipAPI_pyqcamotor->api_convert_from_void_ptr_and_size
#define sipConvertFromConstVoidPtrAndSize   sipAPI_pyqcamotor->api_convert_from_const_void_ptr_and_size
#define sipInvokeSlot               sipAPI_pyqcamotor->api_invoke_slot
#define sipInvokeSlotEx             sipAPI_pyqcamotor->api_invoke_slot_ex
#define sipSaveSlot                 sipAPI_pyqcamotor->api_save_slot
#define sipClearAnySlotReference    sipAPI_pyqcamotor->api_clear_any_slot_reference
#define sipVisitSlot                sipAPI_pyqcamotor->api_visit_slot
#define sipWrappedTypeName(wt)      ((wt)->wt_td->td_cname)
#define sipDeprecated               sipAPI_pyqcamotor->api_deprecated
#define sipGetReference             sipAPI_pyqcamotor->api_get_reference
#define sipKeepReference            sipAPI_pyqcamotor->api_keep_reference
#define sipRegisterProxyResolver    sipAPI_pyqcamotor->api_register_proxy_resolver
#define sipRegisterPyType           sipAPI_pyqcamotor->api_register_py_type
#define sipTypeFromPyTypeObject     sipAPI_pyqcamotor->api_type_from_py_type_object
#define sipTypeScope                sipAPI_pyqcamotor->api_type_scope
#define sipResolveTypedef           sipAPI_pyqcamotor->api_resolve_typedef
#define sipRegisterAttributeGetter  sipAPI_pyqcamotor->api_register_attribute_getter
#define sipIsAPIEnabled             sipAPI_pyqcamotor->api_is_api_enabled
#define sipSetDestroyOnExit         sipAPI_pyqcamotor->api_set_destroy_on_exit
#define sipEnableAutoconversion     sipAPI_pyqcamotor->api_enable_autoconversion
#define sipEnableOverflowChecking   sipAPI_pyqcamotor->api_enable_overflow_checking
#define sipInitMixin                sipAPI_pyqcamotor->api_init_mixin
#define sipExportModule             sipAPI_pyqcamotor->api_export_module
#define sipInitModule               sipAPI_pyqcamotor->api_init_module
#define sipGetInterpreter           sipAPI_pyqcamotor->api_get_interpreter
#define sipSetNewUserTypeHandler    sipAPI_pyqcamotor->api_set_new_user_type_handler
#define sipSetTypeUserData          sipAPI_pyqcamotor->api_set_type_user_data
#define sipGetTypeUserData          sipAPI_pyqcamotor->api_get_type_user_data
#define sipPyTypeDict               sipAPI_pyqcamotor->api_py_type_dict
#define sipPyTypeName               sipAPI_pyqcamotor->api_py_type_name
#define sipGetCFunction             sipAPI_pyqcamotor->api_get_c_function
#define sipGetMethod                sipAPI_pyqcamotor->api_get_method
#define sipFromMethod               sipAPI_pyqcamotor->api_from_method
#define sipGetDate                  sipAPI_pyqcamotor->api_get_date
#define sipFromDate                 sipAPI_pyqcamotor->api_from_date
#define sipGetDateTime              sipAPI_pyqcamotor->api_get_datetime
#define sipFromDateTime             sipAPI_pyqcamotor->api_from_datetime
#define sipGetTime                  sipAPI_pyqcamotor->api_get_time
#define sipFromTime                 sipAPI_pyqcamotor->api_from_time
#define sipIsUserType               sipAPI_pyqcamotor->api_is_user_type
#define sipGetFrame                 sipAPI_pyqcamotor->api_get_frame
#define sipCheckPluginForType       sipAPI_pyqcamotor->api_check_plugin_for_type
#define sipUnicodeNew               sipAPI_pyqcamotor->api_unicode_new
#define sipUnicodeWrite             sipAPI_pyqcamotor->api_unicode_write
#define sipUnicodeData              sipAPI_pyqcamotor->api_unicode_data
#define sipGetBufferInfo            sipAPI_pyqcamotor->api_get_buffer_info
#define sipReleaseBufferInfo        sipAPI_pyqcamotor->api_release_buffer_info
#define sipIsOwnedByPython          sipAPI_pyqcamotor->api_is_owned_by_python
#define sipIsDerivedClass           sipAPI_pyqcamotor->api_is_derived_class
#define sipGetUserObject            sipAPI_pyqcamotor->api_get_user_object
#define sipSetUserObject            sipAPI_pyqcamotor->api_set_user_object
#define sipRegisterEventHandler     sipAPI_pyqcamotor->api_register_event_handler
#define sipLong_AsChar              sipAPI_pyqcamotor->api_long_as_char
#define sipLong_AsSignedChar        sipAPI_pyqcamotor->api_long_as_signed_char
#define sipLong_AsUnsignedChar      sipAPI_pyqcamotor->api_long_as_unsigned_char
#define sipLong_AsShort             sipAPI_pyqcamotor->api_long_as_short
#define sipLong_AsUnsignedShort     sipAPI_pyqcamotor->api_long_as_unsigned_short
#define sipLong_AsInt               sipAPI_pyqcamotor->api_long_as_int
#define sipLong_AsUnsignedInt       sipAPI_pyqcamotor->api_long_as_unsigned_int
#define sipLong_AsLong              sipAPI_pyqcamotor->api_long_as_long
#define sipLong_AsUnsignedLong      sipAPI_pyqcamotor->api_long_as_unsigned_long
#define sipLong_AsLongLong          sipAPI_pyqcamotor->api_long_as_long_long
#define sipLong_AsUnsignedLongLong  sipAPI_pyqcamotor->api_long_as_unsigned_long_long
#define sipLong_AsSizeT             sipAPI_pyqcamotor->api_long_as_size_t

/* These are deprecated. */
#define sipMapStringToClass         sipAPI_pyqcamotor->api_map_string_to_class
#define sipMapIntToClass            sipAPI_pyqcamotor->api_map_int_to_class
#define sipFindClass                sipAPI_pyqcamotor->api_find_class
#define sipFindMappedType           sipAPI_pyqcamotor->api_find_mapped_type
#define sipConvertToArray           sipAPI_pyqcamotor->api_convert_to_array
#define sipConvertToTypedArray      sipAPI_pyqcamotor->api_convert_to_typed_array
#define sipEnableGC                 sipAPI_pyqcamotor->api_enable_gc
#define sipPrintObject              sipAPI_pyqcamotor->api_print_object
#define sipWrapper_Check(w)         PyObject_TypeCheck((w), sipAPI_pyqcamotor->api_wrapper_type)
#define sipGetWrapper(p, wt)        sipGetPyObject((p), (wt)->wt_td)
#define sipReleaseInstance(p, wt, s)    sipReleaseType((p), (wt)->wt_td, (s))
#define sipReleaseMappedType        sipReleaseType
#define sipCanConvertToInstance(o, wt, f)   sipCanConvertToType((o), (wt)->wt_td, (f))
#define sipCanConvertToMappedType   sipCanConvertToType
#define sipConvertToInstance(o, wt, t, f, s, e)     sipConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipConvertToMappedType      sipConvertToType
#define sipForceConvertToInstance(o, wt, t, f, s, e)    sipForceConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipForceConvertToMappedType sipForceConvertToType
#define sipConvertFromInstance(p, wt, t)    sipConvertFromType((p), (wt)->wt_td, (t))
#define sipConvertFromMappedType    sipConvertFromType
#define sipConvertFromNamedEnum(v, pt)  sipConvertFromEnum((v), ((sipEnumTypeObject *)(pt))->type)
#define sipConvertFromNewInstance(p, wt, t) sipConvertFromNewType((p), (wt)->wt_td, (t))

/* The strings used by this module. */
extern const char sipStrings_pyqcamotor[];

#define sipType_QCaMotor sipExportedTypes_pyqcamotor[0]
#define sipClass_QCaMotor sipExportedTypes_pyqcamotor[0]->u.td_wrapper_type

#define sipType_QCaMotor_MotionExit sipExportedTypes_pyqcamotor[2]
#define sipEnum_QCaMotor_MotionExit sipExportedTypes_pyqcamotor[2]->u.td_py_type

#define sipType_QCaMotor_Direction sipExportedTypes_pyqcamotor[1]
#define sipEnum_QCaMotor_Direction sipExportedTypes_pyqcamotor[1]->u.td_py_type

#define sipType_QCaMotor_OffMode sipExportedTypes_pyqcamotor[3]
#define sipEnum_QCaMotor_OffMode sipExportedTypes_pyqcamotor[3]->u.td_py_type

#define sipType_QCaMotor_SuMode sipExportedTypes_pyqcamotor[5]
#define sipEnum_QCaMotor_SuMode sipExportedTypes_pyqcamotor[5]->u.td_py_type

#define sipType_QCaMotor_SpmgMode sipExportedTypes_pyqcamotor[4]
#define sipEnum_QCaMotor_SpmgMode sipExportedTypes_pyqcamotor[4]->u.td_py_type

extern sipClassTypeDef sipTypeDef_pyqcamotor_QCaMotor;

/* The SIP API, this module's API and the APIs of any imported modules. */
extern const sipAPIDef *sipAPI_pyqcamotor;
extern sipExportedModuleDef sipModuleAPI_pyqcamotor;
extern sipTypeDef *sipExportedTypes_pyqcamotor[];

#define sipType_QObject sipImportedTypes_pyqcamotor_QtCore[3].it_td
#define sipClass_QObject sipImportedTypes_pyqcamotor_QtCore[3].it_td->u.td_wrapper_type

#define sipType_QEvent sipImportedTypes_pyqcamotor_QtCore[1].it_td
#define sipClass_QEvent sipImportedTypes_pyqcamotor_QtCore[1].it_td->u.td_wrapper_type

#define sipType_QTimerEvent sipImportedTypes_pyqcamotor_QtCore[5].it_td
#define sipClass_QTimerEvent sipImportedTypes_pyqcamotor_QtCore[5].it_td->u.td_wrapper_type

#define sipType_QChildEvent sipImportedTypes_pyqcamotor_QtCore[0].it_td
#define sipClass_QChildEvent sipImportedTypes_pyqcamotor_QtCore[0].it_td->u.td_wrapper_type

#define sipType_QMetaMethod sipImportedTypes_pyqcamotor_QtCore[2].it_td
#define sipClass_QMetaMethod sipImportedTypes_pyqcamotor_QtCore[2].it_td->u.td_wrapper_type

#define sipType_QString sipImportedTypes_pyqcamotor_QtCore[4].it_td
extern sipImportedTypeDef sipImportedTypes_pyqcamotor_QtCore[];
extern sipImportedVirtErrorHandlerDef sipImportedVirtErrorHandlers_pyqcamotor_QtCore[];

typedef const QMetaObject *(*sip_qt_metaobject_func)(sipSimpleWrapper *,sipTypeDef *);
extern sip_qt_metaobject_func sip_pyqcamotor_qt_metaobject;

typedef int (*sip_qt_metacall_func)(sipSimpleWrapper *,sipTypeDef *,QMetaObject::Call,int,void **);
extern sip_qt_metacall_func sip_pyqcamotor_qt_metacall;

typedef bool (*sip_qt_metacast_func)(sipSimpleWrapper *, const sipTypeDef *, const char *, void **);
extern sip_qt_metacast_func sip_pyqcamotor_qt_metacast;

#endif
