/*
 * Internal module API header file.
 *
 * Generated by SIP 4.19.16
 */

#ifndef _pyqcamotorguiAPI_H
#define _pyqcamotorguiAPI_H

#include <sip.h>

#include <QMetaType>
#include <QThread>

/* These are the qualifiers that are enabled. */
#define SIP_FEATURE_PyQt_MacOSXOnly
#define SIP_FEATURE_PyQt_Process
#define SIP_FEATURE_PyQt_NotBootstrapped
#define SIP_FEATURE_PyQt_Desktop_OpenGL
#define SIP_FEATURE_PyQt_OpenGL
#define SIP_FEATURE_PyQt_RawFont
#define SIP_FEATURE_PyQt_PrintPreviewDialog
#define SIP_FEATURE_PyQt_PrintPreviewWidget
#define SIP_FEATURE_PyQt_Printer
#define SIP_FEATURE_PyQt_PrintDialog
#define SIP_FEATURE_Py_v3
#define SIP_FEATURE_PyQt_qreal_double
#define SIP_FEATURE_PyQt_SSL
#define SIP_FEATURE_PyQt_SessionManager
#define SIP_FEATURE_PyQt_Accessibility
#define SIP_PLATFORM_WS_X11


/*
 * Convenient names to refer to various strings defined in this module.
 * Only the class names are part of the public API.
 */
#define sipNameNr_QCaMotorGUI__ViewMode 0
#define sipName_QCaMotorGUI__ViewMode &sipStrings_pyqcamotorgui[0]
#define sipNameNr_mouseDoubleClickEvent 22
#define sipName_mouseDoubleClickEvent &sipStrings_pyqcamotorgui[22]
#define sipNameNr_configsSearchBaseDir 44
#define sipName_configsSearchBaseDir &sipStrings_pyqcamotorgui[44]
#define sipNameNr_focusPreviousChild 65
#define sipName_focusPreviousChild &sipStrings_pyqcamotorgui[65]
#define sipNameNr_focusNextPrevChild 84
#define sipName_focusNextPrevChild &sipStrings_pyqcamotorgui[84]
#define sipNameNr_ioPositionChanged 103
#define sipName_ioPositionChanged &sipStrings_pyqcamotorgui[103]
#define sipNameNr_destroySubWindows 121
#define sipName_destroySubWindows &sipStrings_pyqcamotorgui[121]
#define sipNameNr_hasHeightForWidth 139
#define sipName_hasHeightForWidth &sipStrings_pyqcamotorgui[139]
#define sipNameNr_mouseReleaseEvent 157
#define sipName_mouseReleaseEvent &sipStrings_pyqcamotorgui[157]
#define sipNameNr_isSignalConnected 175
#define sipName_isSignalConnected &sipStrings_pyqcamotorgui[175]
#define sipNameNr_senderSignalIndex 193
#define sipName_senderSignalIndex &sipStrings_pyqcamotorgui[193]
#define sipNameNr_destroyOldWindow 211
#define sipName_destroyOldWindow &sipStrings_pyqcamotorgui[211]
#define sipNameNr_initializeWindow 228
#define sipName_initializeWindow &sipStrings_pyqcamotorgui[228]
#define sipNameNr_updateMicroFocus 245
#define sipName_updateMicroFocus &sipStrings_pyqcamotorgui[245]
#define sipNameNr_contextMenuEvent 262
#define sipName_contextMenuEvent &sipStrings_pyqcamotorgui[262]
#define sipNameNr_inputMethodEvent 279
#define sipName_inputMethodEvent &sipStrings_pyqcamotorgui[279]
#define sipNameNr_inputMethodQuery 296
#define sipName_inputMethodQuery &sipStrings_pyqcamotorgui[296]
#define sipNameNr_disconnectNotify 313
#define sipName_disconnectNotify &sipStrings_pyqcamotorgui[313]
#define sipNameNr_minimumSizeHint 330
#define sipName_minimumSizeHint &sipStrings_pyqcamotorgui[330]
#define sipNameNr_mousePressEvent 346
#define sipName_mousePressEvent &sipStrings_pyqcamotorgui[346]
#define sipNameNr_keyReleaseEvent 362
#define sipName_keyReleaseEvent &sipStrings_pyqcamotorgui[362]
#define sipNameNr_currentPosition 378
#define sipName_currentPosition &sipStrings_pyqcamotorgui[378]
#define sipNameNr_pvListBaseName 394
#define sipName_pvListBaseName &sipStrings_pyqcamotorgui[394]
#define sipNameNr_focusNextChild 409
#define sipName_focusNextChild &sipStrings_pyqcamotorgui[409]
#define sipNameNr_heightForWidth 424
#define sipName_heightForWidth &sipStrings_pyqcamotorgui[424]
#define sipNameNr_dragLeaveEvent 439
#define sipName_dragLeaveEvent &sipStrings_pyqcamotorgui[439]
#define sipNameNr_dragEnterEvent 454
#define sipName_dragEnterEvent &sipStrings_pyqcamotorgui[454]
#define sipNameNr_mouseMoveEvent 469
#define sipName_mouseMoveEvent &sipStrings_pyqcamotorgui[469]
#define sipNameNr_changedSignal 484
#define sipName_changedSignal &sipStrings_pyqcamotorgui[484]
#define sipNameNr_sharedPainter 498
#define sipName_sharedPainter &sipStrings_pyqcamotorgui[498]
#define sipNameNr_destroyWindow 512
#define sipName_destroyWindow &sipStrings_pyqcamotorgui[512]
#define sipNameNr_thresholdTime 526
#define sipName_thresholdTime &sipStrings_pyqcamotorgui[526]
#define sipNameNr_dragMoveEvent 540
#define sipName_dragMoveEvent &sipStrings_pyqcamotorgui[540]
#define sipNameNr_keyPressEvent 554
#define sipName_keyPressEvent &sipStrings_pyqcamotorgui[554]
#define sipNameNr_focusOutEvent 568
#define sipName_focusOutEvent &sipStrings_pyqcamotorgui[568]
#define sipNameNr_connectNotify 316
#define sipName_connectNotify &sipStrings_pyqcamotorgui[316]
#define sipNameNr_pyqcamotorgui 582
#define sipName_pyqcamotorgui &sipStrings_pyqcamotorgui[582]
#define sipNameNr_focusInEvent 596
#define sipName_focusInEvent &sipStrings_pyqcamotorgui[596]
#define sipNameNr_showPvSetup 609
#define sipName_showPvSetup &sipStrings_pyqcamotorgui[609]
#define sipNameNr_setupButton 621
#define sipName_setupButton &sipStrings_pyqcamotorgui[621]
#define sipNameNr_QCaMotorGUI 633
#define sipName_QCaMotorGUI &sipStrings_pyqcamotorgui[633]
#define sipNameNr_initPainter 645
#define sipName_initPainter &sipStrings_pyqcamotorgui[645]
#define sipNameNr_nativeEvent 657
#define sipName_nativeEvent &sipStrings_pyqcamotorgui[657]
#define sipNameNr_actionEvent 669
#define sipName_actionEvent &sipStrings_pyqcamotorgui[669]
#define sipNameNr_setViewMode 681
#define sipName_setViewMode &sipStrings_pyqcamotorgui[681]
#define sipNameNr_changeEvent 693
#define sipName_changeEvent &sipStrings_pyqcamotorgui[693]
#define sipNameNr_tabletEvent 705
#define sipName_tabletEvent &sipStrings_pyqcamotorgui[705]
#define sipNameNr_resizeEvent 717
#define sipName_resizeEvent &sipStrings_pyqcamotorgui[717]
#define sipNameNr_paintEngine 729
#define sipName_paintEngine &sipStrings_pyqcamotorgui[729]
#define sipNameNr_customEvent 741
#define sipName_customEvent &sipStrings_pyqcamotorgui[741]
#define sipNameNr_eventFilter 753
#define sipName_eventFilter &sipStrings_pyqcamotorgui[753]
#define sipNameNr_configsExt 765
#define sipName_configsExt &sipStrings_pyqcamotorgui[765]
#define sipNameNr_enterEvent 776
#define sipName_enterEvent &sipStrings_pyqcamotorgui[776]
#define sipNameNr_leaveEvent 787
#define sipName_leaveEvent &sipStrings_pyqcamotorgui[787]
#define sipNameNr_constraint 798
#define sipName_constraint &sipStrings_pyqcamotorgui[798]
#define sipNameNr_closeEvent 809
#define sipName_closeEvent &sipStrings_pyqcamotorgui[809]
#define sipNameNr_repeatTime 820
#define sipName_repeatTime &sipStrings_pyqcamotorgui[820]
#define sipNameNr_wheelEvent 831
#define sipName_wheelEvent &sipStrings_pyqcamotorgui[831]
#define sipNameNr_columnSpan 842
#define sipName_columnSpan &sipStrings_pyqcamotorgui[842]
#define sipNameNr_paintEvent 853
#define sipName_paintEvent &sipStrings_pyqcamotorgui[853]
#define sipNameNr_setVisible 864
#define sipName_setVisible &sipStrings_pyqcamotorgui[864]
#define sipNameNr_childEvent 875
#define sipName_childEvent &sipStrings_pyqcamotorgui[875]
#define sipNameNr_timerEvent 886
#define sipName_timerEvent &sipStrings_pyqcamotorgui[886]
#define sipNameNr_showSetup 897
#define sipName_showSetup &sipStrings_pyqcamotorgui[897]
#define sipNameNr_dropEvent 907
#define sipName_dropEvent &sipStrings_pyqcamotorgui[907]
#define sipNameNr_hideEvent 917
#define sipName_hideEvent &sipStrings_pyqcamotorgui[917]
#define sipNameNr_showEvent 927
#define sipName_showEvent &sipStrings_pyqcamotorgui[927]
#define sipNameNr_moveEvent 937
#define sipName_moveEvent &sipStrings_pyqcamotorgui[937]
#define sipNameNr_alignment 947
#define sipName_alignment &sipStrings_pyqcamotorgui[947]
#define sipNameNr_receivers 957
#define sipName_receivers &sipStrings_pyqcamotorgui[957]
#define sipNameNr_ViewMode 13
#define sipName_ViewMode &sipStrings_pyqcamotorgui[13]
#define sipNameNr_sizeHint 967
#define sipName_sizeHint &sipStrings_pyqcamotorgui[967]
#define sipNameNr_property 976
#define sipName_property &sipStrings_pyqcamotorgui[976]
#define sipNameNr_rowSpan 985
#define sipName_rowSpan &sipStrings_pyqcamotorgui[985]
#define sipNameNr_destroy 993
#define sipName_destroy &sipStrings_pyqcamotorgui[993]
#define sipNameNr_devType 1001
#define sipName_devType &sipStrings_pyqcamotorgui[1001]
#define sipNameNr_enabled 1009
#define sipName_enabled &sipStrings_pyqcamotorgui[1009]
#define sipNameNr_CONFIG 1017
#define sipName_CONFIG &sipStrings_pyqcamotorgui[1017]
#define sipNameNr_metric 1024
#define sipName_metric &sipStrings_pyqcamotorgui[1024]
#define sipNameNr_window 1031
#define sipName_window &sipStrings_pyqcamotorgui[1031]
#define sipNameNr_create 1038
#define sipName_create &sipStrings_pyqcamotorgui[1038]
#define sipNameNr_sender 1045
#define sipName_sender &sipStrings_pyqcamotorgui[1045]
#define sipNameNr_system 1052
#define sipName_system &sipStrings_pyqcamotorgui[1052]
#define sipNameNr_offset 1059
#define sipName_offset &sipStrings_pyqcamotorgui[1059]
#define sipNameNr_column 1066
#define sipName_column &sipStrings_pyqcamotorgui[1066]
#define sipNameNr_object 1073
#define sipName_object &sipStrings_pyqcamotorgui[1073]
#define sipNameNr_motor 1080
#define sipName_motor &sipStrings_pyqcamotorgui[1080]
#define sipNameNr_EPICS 1086
#define sipName_EPICS &sipStrings_pyqcamotorgui[1086]
#define sipNameNr_COMFO 1092
#define sipName_COMFO &sipStrings_pyqcamotorgui[1092]
#define sipNameNr_SETPV 1098
#define sipName_SETPV &sipStrings_pyqcamotorgui[1098]
#define sipNameNr_roles 1104
#define sipName_roles &sipStrings_pyqcamotorgui[1104]
#define sipNameNr_event 1110
#define sipName_event &sipStrings_pyqcamotorgui[1110]
#define sipNameNr_MINI 1116
#define sipName_MINI &sipStrings_pyqcamotorgui[1116]
#define sipNameNr_lock 1121
#define sipName_lock &sipStrings_pyqcamotorgui[1121]
#define sipNameNr_mode 1126
#define sipName_mode &sipStrings_pyqcamotorgui[1126]

#define sipMalloc                   sipAPI_pyqcamotorgui->api_malloc
#define sipFree                     sipAPI_pyqcamotorgui->api_free
#define sipBuildResult              sipAPI_pyqcamotorgui->api_build_result
#define sipCallMethod               sipAPI_pyqcamotorgui->api_call_method
#define sipCallProcedureMethod      sipAPI_pyqcamotorgui->api_call_procedure_method
#define sipCallErrorHandler         sipAPI_pyqcamotorgui->api_call_error_handler
#define sipParseResultEx            sipAPI_pyqcamotorgui->api_parse_result_ex
#define sipParseResult              sipAPI_pyqcamotorgui->api_parse_result
#define sipParseArgs                sipAPI_pyqcamotorgui->api_parse_args
#define sipParseKwdArgs             sipAPI_pyqcamotorgui->api_parse_kwd_args
#define sipParsePair                sipAPI_pyqcamotorgui->api_parse_pair
#define sipInstanceDestroyed        sipAPI_pyqcamotorgui->api_instance_destroyed
#define sipInstanceDestroyedEx      sipAPI_pyqcamotorgui->api_instance_destroyed_ex
#define sipConvertFromSequenceIndex sipAPI_pyqcamotorgui->api_convert_from_sequence_index
#define sipConvertFromSliceObject   sipAPI_pyqcamotorgui->api_convert_from_slice_object
#define sipConvertFromVoidPtr       sipAPI_pyqcamotorgui->api_convert_from_void_ptr
#define sipConvertToVoidPtr         sipAPI_pyqcamotorgui->api_convert_to_void_ptr
#define sipAddException             sipAPI_pyqcamotorgui->api_add_exception
#define sipNoFunction               sipAPI_pyqcamotorgui->api_no_function
#define sipNoMethod                 sipAPI_pyqcamotorgui->api_no_method
#define sipAbstractMethod           sipAPI_pyqcamotorgui->api_abstract_method
#define sipBadClass                 sipAPI_pyqcamotorgui->api_bad_class
#define sipBadCatcherResult         sipAPI_pyqcamotorgui->api_bad_catcher_result
#define sipBadCallableArg           sipAPI_pyqcamotorgui->api_bad_callable_arg
#define sipBadOperatorArg           sipAPI_pyqcamotorgui->api_bad_operator_arg
#define sipTrace                    sipAPI_pyqcamotorgui->api_trace
#define sipTransferBack             sipAPI_pyqcamotorgui->api_transfer_back
#define sipTransferTo               sipAPI_pyqcamotorgui->api_transfer_to
#define sipTransferBreak            sipAPI_pyqcamotorgui->api_transfer_break
#define sipSimpleWrapper_Type       sipAPI_pyqcamotorgui->api_simplewrapper_type
#define sipWrapper_Type             sipAPI_pyqcamotorgui->api_wrapper_type
#define sipWrapperType_Type         sipAPI_pyqcamotorgui->api_wrappertype_type
#define sipVoidPtr_Type             sipAPI_pyqcamotorgui->api_voidptr_type
#define sipGetPyObject              sipAPI_pyqcamotorgui->api_get_pyobject
#define sipGetAddress               sipAPI_pyqcamotorgui->api_get_address
#define sipGetMixinAddress          sipAPI_pyqcamotorgui->api_get_mixin_address
#define sipGetCppPtr                sipAPI_pyqcamotorgui->api_get_cpp_ptr
#define sipGetComplexCppPtr         sipAPI_pyqcamotorgui->api_get_complex_cpp_ptr
#define sipIsPyMethod               sipAPI_pyqcamotorgui->api_is_py_method
#define sipCallHook                 sipAPI_pyqcamotorgui->api_call_hook
#define sipEndThread                sipAPI_pyqcamotorgui->api_end_thread
#define sipConnectRx                sipAPI_pyqcamotorgui->api_connect_rx
#define sipDisconnectRx             sipAPI_pyqcamotorgui->api_disconnect_rx
#define sipRaiseUnknownException    sipAPI_pyqcamotorgui->api_raise_unknown_exception
#define sipRaiseTypeException       sipAPI_pyqcamotorgui->api_raise_type_exception
#define sipBadLengthForSlice        sipAPI_pyqcamotorgui->api_bad_length_for_slice
#define sipAddTypeInstance          sipAPI_pyqcamotorgui->api_add_type_instance
#define sipFreeSipslot              sipAPI_pyqcamotorgui->api_free_sipslot
#define sipSameSlot                 sipAPI_pyqcamotorgui->api_same_slot
#define sipPySlotExtend             sipAPI_pyqcamotorgui->api_pyslot_extend
#define sipConvertRx                sipAPI_pyqcamotorgui->api_convert_rx
#define sipAddDelayedDtor           sipAPI_pyqcamotorgui->api_add_delayed_dtor
#define sipCanConvertToType         sipAPI_pyqcamotorgui->api_can_convert_to_type
#define sipConvertToType            sipAPI_pyqcamotorgui->api_convert_to_type
#define sipForceConvertToType       sipAPI_pyqcamotorgui->api_force_convert_to_type
#define sipCanConvertToEnum         sipAPI_pyqcamotorgui->api_can_convert_to_enum
#define sipConvertToEnum            sipAPI_pyqcamotorgui->api_convert_to_enum
#define sipConvertToBool            sipAPI_pyqcamotorgui->api_convert_to_bool
#define sipReleaseType              sipAPI_pyqcamotorgui->api_release_type
#define sipConvertFromType          sipAPI_pyqcamotorgui->api_convert_from_type
#define sipConvertFromNewType       sipAPI_pyqcamotorgui->api_convert_from_new_type
#define sipConvertFromNewPyType     sipAPI_pyqcamotorgui->api_convert_from_new_pytype
#define sipConvertFromEnum          sipAPI_pyqcamotorgui->api_convert_from_enum
#define sipGetState                 sipAPI_pyqcamotorgui->api_get_state
#define sipExportSymbol             sipAPI_pyqcamotorgui->api_export_symbol
#define sipImportSymbol             sipAPI_pyqcamotorgui->api_import_symbol
#define sipFindType                 sipAPI_pyqcamotorgui->api_find_type
#define sipFindNamedEnum            sipAPI_pyqcamotorgui->api_find_named_enum
#define sipBytes_AsChar             sipAPI_pyqcamotorgui->api_bytes_as_char
#define sipBytes_AsString           sipAPI_pyqcamotorgui->api_bytes_as_string
#define sipString_AsASCIIChar       sipAPI_pyqcamotorgui->api_string_as_ascii_char
#define sipString_AsASCIIString     sipAPI_pyqcamotorgui->api_string_as_ascii_string
#define sipString_AsLatin1Char      sipAPI_pyqcamotorgui->api_string_as_latin1_char
#define sipString_AsLatin1String    sipAPI_pyqcamotorgui->api_string_as_latin1_string
#define sipString_AsUTF8Char        sipAPI_pyqcamotorgui->api_string_as_utf8_char
#define sipString_AsUTF8String      sipAPI_pyqcamotorgui->api_string_as_utf8_string
#define sipUnicode_AsWChar          sipAPI_pyqcamotorgui->api_unicode_as_wchar
#define sipUnicode_AsWString        sipAPI_pyqcamotorgui->api_unicode_as_wstring
#define sipConvertFromConstVoidPtr  sipAPI_pyqcamotorgui->api_convert_from_const_void_ptr
#define sipConvertFromVoidPtrAndSize    sipAPI_pyqcamotorgui->api_convert_from_void_ptr_and_size
#define sipConvertFromConstVoidPtrAndSize   sipAPI_pyqcamotorgui->api_convert_from_const_void_ptr_and_size
#define sipInvokeSlot               sipAPI_pyqcamotorgui->api_invoke_slot
#define sipInvokeSlotEx             sipAPI_pyqcamotorgui->api_invoke_slot_ex
#define sipSaveSlot                 sipAPI_pyqcamotorgui->api_save_slot
#define sipClearAnySlotReference    sipAPI_pyqcamotorgui->api_clear_any_slot_reference
#define sipVisitSlot                sipAPI_pyqcamotorgui->api_visit_slot
#define sipWrappedTypeName(wt)      ((wt)->wt_td->td_cname)
#define sipDeprecated               sipAPI_pyqcamotorgui->api_deprecated
#define sipGetReference             sipAPI_pyqcamotorgui->api_get_reference
#define sipKeepReference            sipAPI_pyqcamotorgui->api_keep_reference
#define sipRegisterProxyResolver    sipAPI_pyqcamotorgui->api_register_proxy_resolver
#define sipRegisterPyType           sipAPI_pyqcamotorgui->api_register_py_type
#define sipTypeFromPyTypeObject     sipAPI_pyqcamotorgui->api_type_from_py_type_object
#define sipTypeScope                sipAPI_pyqcamotorgui->api_type_scope
#define sipResolveTypedef           sipAPI_pyqcamotorgui->api_resolve_typedef
#define sipRegisterAttributeGetter  sipAPI_pyqcamotorgui->api_register_attribute_getter
#define sipIsAPIEnabled             sipAPI_pyqcamotorgui->api_is_api_enabled
#define sipSetDestroyOnExit         sipAPI_pyqcamotorgui->api_set_destroy_on_exit
#define sipEnableAutoconversion     sipAPI_pyqcamotorgui->api_enable_autoconversion
#define sipEnableOverflowChecking   sipAPI_pyqcamotorgui->api_enable_overflow_checking
#define sipInitMixin                sipAPI_pyqcamotorgui->api_init_mixin
#define sipExportModule             sipAPI_pyqcamotorgui->api_export_module
#define sipInitModule               sipAPI_pyqcamotorgui->api_init_module
#define sipGetInterpreter           sipAPI_pyqcamotorgui->api_get_interpreter
#define sipSetNewUserTypeHandler    sipAPI_pyqcamotorgui->api_set_new_user_type_handler
#define sipSetTypeUserData          sipAPI_pyqcamotorgui->api_set_type_user_data
#define sipGetTypeUserData          sipAPI_pyqcamotorgui->api_get_type_user_data
#define sipPyTypeDict               sipAPI_pyqcamotorgui->api_py_type_dict
#define sipPyTypeName               sipAPI_pyqcamotorgui->api_py_type_name
#define sipGetCFunction             sipAPI_pyqcamotorgui->api_get_c_function
#define sipGetMethod                sipAPI_pyqcamotorgui->api_get_method
#define sipFromMethod               sipAPI_pyqcamotorgui->api_from_method
#define sipGetDate                  sipAPI_pyqcamotorgui->api_get_date
#define sipFromDate                 sipAPI_pyqcamotorgui->api_from_date
#define sipGetDateTime              sipAPI_pyqcamotorgui->api_get_datetime
#define sipFromDateTime             sipAPI_pyqcamotorgui->api_from_datetime
#define sipGetTime                  sipAPI_pyqcamotorgui->api_get_time
#define sipFromTime                 sipAPI_pyqcamotorgui->api_from_time
#define sipIsUserType               sipAPI_pyqcamotorgui->api_is_user_type
#define sipGetFrame                 sipAPI_pyqcamotorgui->api_get_frame
#define sipCheckPluginForType       sipAPI_pyqcamotorgui->api_check_plugin_for_type
#define sipUnicodeNew               sipAPI_pyqcamotorgui->api_unicode_new
#define sipUnicodeWrite             sipAPI_pyqcamotorgui->api_unicode_write
#define sipUnicodeData              sipAPI_pyqcamotorgui->api_unicode_data
#define sipGetBufferInfo            sipAPI_pyqcamotorgui->api_get_buffer_info
#define sipReleaseBufferInfo        sipAPI_pyqcamotorgui->api_release_buffer_info
#define sipIsOwnedByPython          sipAPI_pyqcamotorgui->api_is_owned_by_python
#define sipIsDerivedClass           sipAPI_pyqcamotorgui->api_is_derived_class
#define sipGetUserObject            sipAPI_pyqcamotorgui->api_get_user_object
#define sipSetUserObject            sipAPI_pyqcamotorgui->api_set_user_object
#define sipRegisterEventHandler     sipAPI_pyqcamotorgui->api_register_event_handler
#define sipLong_AsChar              sipAPI_pyqcamotorgui->api_long_as_char
#define sipLong_AsSignedChar        sipAPI_pyqcamotorgui->api_long_as_signed_char
#define sipLong_AsUnsignedChar      sipAPI_pyqcamotorgui->api_long_as_unsigned_char
#define sipLong_AsShort             sipAPI_pyqcamotorgui->api_long_as_short
#define sipLong_AsUnsignedShort     sipAPI_pyqcamotorgui->api_long_as_unsigned_short
#define sipLong_AsInt               sipAPI_pyqcamotorgui->api_long_as_int
#define sipLong_AsUnsignedInt       sipAPI_pyqcamotorgui->api_long_as_unsigned_int
#define sipLong_AsLong              sipAPI_pyqcamotorgui->api_long_as_long
#define sipLong_AsUnsignedLong      sipAPI_pyqcamotorgui->api_long_as_unsigned_long
#define sipLong_AsLongLong          sipAPI_pyqcamotorgui->api_long_as_long_long
#define sipLong_AsUnsignedLongLong  sipAPI_pyqcamotorgui->api_long_as_unsigned_long_long
#define sipLong_AsSizeT             sipAPI_pyqcamotorgui->api_long_as_size_t

/* These are deprecated. */
#define sipMapStringToClass         sipAPI_pyqcamotorgui->api_map_string_to_class
#define sipMapIntToClass            sipAPI_pyqcamotorgui->api_map_int_to_class
#define sipFindClass                sipAPI_pyqcamotorgui->api_find_class
#define sipFindMappedType           sipAPI_pyqcamotorgui->api_find_mapped_type
#define sipConvertToArray           sipAPI_pyqcamotorgui->api_convert_to_array
#define sipConvertToTypedArray      sipAPI_pyqcamotorgui->api_convert_to_typed_array
#define sipEnableGC                 sipAPI_pyqcamotorgui->api_enable_gc
#define sipPrintObject              sipAPI_pyqcamotorgui->api_print_object
#define sipWrapper_Check(w)         PyObject_TypeCheck((w), sipAPI_pyqcamotorgui->api_wrapper_type)
#define sipGetWrapper(p, wt)        sipGetPyObject((p), (wt)->wt_td)
#define sipReleaseInstance(p, wt, s)    sipReleaseType((p), (wt)->wt_td, (s))
#define sipReleaseMappedType        sipReleaseType
#define sipCanConvertToInstance(o, wt, f)   sipCanConvertToType((o), (wt)->wt_td, (f))
#define sipCanConvertToMappedType   sipCanConvertToType
#define sipConvertToInstance(o, wt, t, f, s, e)     sipConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipConvertToMappedType      sipConvertToType
#define sipForceConvertToInstance(o, wt, t, f, s, e)    sipForceConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipForceConvertToMappedType sipForceConvertToType
#define sipConvertFromInstance(p, wt, t)    sipConvertFromType((p), (wt)->wt_td, (t))
#define sipConvertFromMappedType    sipConvertFromType
#define sipConvertFromNamedEnum(v, pt)  sipConvertFromEnum((v), ((sipEnumTypeObject *)(pt))->type)
#define sipConvertFromNewInstance(p, wt, t) sipConvertFromNewType((p), (wt)->wt_td, (t))

/* The strings used by this module. */
extern const char sipStrings_pyqcamotorgui[];

#define sipType_QCaMotorGUI sipExportedTypes_pyqcamotorgui[0]
#define sipClass_QCaMotorGUI sipExportedTypes_pyqcamotorgui[0]->u.td_wrapper_type

#define sipType_QCaMotorGUI_ViewMode sipExportedTypes_pyqcamotorgui[1]
#define sipEnum_QCaMotorGUI_ViewMode sipExportedTypes_pyqcamotorgui[1]->u.td_py_type

extern sipClassTypeDef sipTypeDef_pyqcamotorgui_QCaMotorGUI;

/* The SIP API, this module's API and the APIs of any imported modules. */
extern const sipAPIDef *sipAPI_pyqcamotorgui;
extern sipExportedModuleDef sipModuleAPI_pyqcamotorgui;
extern sipTypeDef *sipExportedTypes_pyqcamotorgui[];

#define sipType_Qt_InputMethodQuery sipImportedTypes_pyqcamotorgui_QtCore[9].it_td
#define sipEnum_Qt_InputMethodQuery sipImportedTypes_pyqcamotorgui_QtCore[9].it_td->u.td_py_type

#define sipType_QObject sipImportedTypes_pyqcamotorgui_QtCore[4].it_td
#define sipClass_QObject sipImportedTypes_pyqcamotorgui_QtCore[4].it_td->u.td_wrapper_type

#define sipType_QByteArray sipImportedTypes_pyqcamotorgui_QtCore[0].it_td
#define sipClass_QByteArray sipImportedTypes_pyqcamotorgui_QtCore[0].it_td->u.td_wrapper_type

#define sipType_QEvent sipImportedTypes_pyqcamotorgui_QtCore[2].it_td
#define sipClass_QEvent sipImportedTypes_pyqcamotorgui_QtCore[2].it_td->u.td_wrapper_type

#define sipType_QTimerEvent sipImportedTypes_pyqcamotorgui_QtCore[7].it_td
#define sipClass_QTimerEvent sipImportedTypes_pyqcamotorgui_QtCore[7].it_td->u.td_wrapper_type

#define sipType_QChildEvent sipImportedTypes_pyqcamotorgui_QtCore[1].it_td
#define sipClass_QChildEvent sipImportedTypes_pyqcamotorgui_QtCore[1].it_td->u.td_wrapper_type

#define sipType_QMetaMethod sipImportedTypes_pyqcamotorgui_QtCore[3].it_td
#define sipClass_QMetaMethod sipImportedTypes_pyqcamotorgui_QtCore[3].it_td->u.td_wrapper_type

#define sipType_QSize sipImportedTypes_pyqcamotorgui_QtCore[5].it_td
#define sipClass_QSize sipImportedTypes_pyqcamotorgui_QtCore[5].it_td->u.td_wrapper_type

#define sipType_QVariant sipImportedTypes_pyqcamotorgui_QtCore[8].it_td
#define sipClass_QVariant sipImportedTypes_pyqcamotorgui_QtCore[8].it_td->u.td_wrapper_type

#define sipType_QString sipImportedTypes_pyqcamotorgui_QtCore[6].it_td

#define sipType_quintptr sipImportedTypes_pyqcamotorgui_QtCore[10].it_td
extern sipImportedTypeDef sipImportedTypes_pyqcamotorgui_QtCore[];
extern sipImportedVirtErrorHandlerDef sipImportedVirtErrorHandlers_pyqcamotorgui_QtCore[];

#define sipType_QPaintDevice sipImportedTypes_pyqcamotorgui_QtGui[13].it_td
#define sipClass_QPaintDevice sipImportedTypes_pyqcamotorgui_QtGui[13].it_td->u.td_wrapper_type

#define sipType_QPaintDevice_PaintDeviceMetric sipImportedTypes_pyqcamotorgui_QtGui[14].it_td
#define sipEnum_QPaintDevice_PaintDeviceMetric sipImportedTypes_pyqcamotorgui_QtGui[14].it_td->u.td_py_type

#define sipType_QMouseEvent sipImportedTypes_pyqcamotorgui_QtGui[11].it_td
#define sipClass_QMouseEvent sipImportedTypes_pyqcamotorgui_QtGui[11].it_td->u.td_wrapper_type

#define sipType_QWheelEvent sipImportedTypes_pyqcamotorgui_QtGui[21].it_td
#define sipClass_QWheelEvent sipImportedTypes_pyqcamotorgui_QtGui[21].it_td->u.td_wrapper_type

#define sipType_QTabletEvent sipImportedTypes_pyqcamotorgui_QtGui[20].it_td
#define sipClass_QTabletEvent sipImportedTypes_pyqcamotorgui_QtGui[20].it_td->u.td_wrapper_type

#define sipType_QKeyEvent sipImportedTypes_pyqcamotorgui_QtGui[10].it_td
#define sipClass_QKeyEvent sipImportedTypes_pyqcamotorgui_QtGui[10].it_td->u.td_wrapper_type

#define sipType_QFocusEvent sipImportedTypes_pyqcamotorgui_QtGui[7].it_td
#define sipClass_QFocusEvent sipImportedTypes_pyqcamotorgui_QtGui[7].it_td->u.td_wrapper_type

#define sipType_QPaintEvent sipImportedTypes_pyqcamotorgui_QtGui[16].it_td
#define sipClass_QPaintEvent sipImportedTypes_pyqcamotorgui_QtGui[16].it_td->u.td_wrapper_type

#define sipType_QMoveEvent sipImportedTypes_pyqcamotorgui_QtGui[12].it_td
#define sipClass_QMoveEvent sipImportedTypes_pyqcamotorgui_QtGui[12].it_td->u.td_wrapper_type

#define sipType_QResizeEvent sipImportedTypes_pyqcamotorgui_QtGui[18].it_td
#define sipClass_QResizeEvent sipImportedTypes_pyqcamotorgui_QtGui[18].it_td->u.td_wrapper_type

#define sipType_QCloseEvent sipImportedTypes_pyqcamotorgui_QtGui[1].it_td
#define sipClass_QCloseEvent sipImportedTypes_pyqcamotorgui_QtGui[1].it_td->u.td_wrapper_type

#define sipType_QShowEvent sipImportedTypes_pyqcamotorgui_QtGui[19].it_td
#define sipClass_QShowEvent sipImportedTypes_pyqcamotorgui_QtGui[19].it_td->u.td_wrapper_type

#define sipType_QHideEvent sipImportedTypes_pyqcamotorgui_QtGui[8].it_td
#define sipClass_QHideEvent sipImportedTypes_pyqcamotorgui_QtGui[8].it_td->u.td_wrapper_type

#define sipType_QContextMenuEvent sipImportedTypes_pyqcamotorgui_QtGui[2].it_td
#define sipClass_QContextMenuEvent sipImportedTypes_pyqcamotorgui_QtGui[2].it_td->u.td_wrapper_type

#define sipType_QInputMethodEvent sipImportedTypes_pyqcamotorgui_QtGui[9].it_td
#define sipClass_QInputMethodEvent sipImportedTypes_pyqcamotorgui_QtGui[9].it_td->u.td_wrapper_type

#define sipType_QDropEvent sipImportedTypes_pyqcamotorgui_QtGui[6].it_td
#define sipClass_QDropEvent sipImportedTypes_pyqcamotorgui_QtGui[6].it_td->u.td_wrapper_type

#define sipType_QDragMoveEvent sipImportedTypes_pyqcamotorgui_QtGui[5].it_td
#define sipClass_QDragMoveEvent sipImportedTypes_pyqcamotorgui_QtGui[5].it_td->u.td_wrapper_type

#define sipType_QDragEnterEvent sipImportedTypes_pyqcamotorgui_QtGui[3].it_td
#define sipClass_QDragEnterEvent sipImportedTypes_pyqcamotorgui_QtGui[3].it_td->u.td_wrapper_type

#define sipType_QDragLeaveEvent sipImportedTypes_pyqcamotorgui_QtGui[4].it_td
#define sipClass_QDragLeaveEvent sipImportedTypes_pyqcamotorgui_QtGui[4].it_td->u.td_wrapper_type

#define sipType_QActionEvent sipImportedTypes_pyqcamotorgui_QtGui[0].it_td
#define sipClass_QActionEvent sipImportedTypes_pyqcamotorgui_QtGui[0].it_td->u.td_wrapper_type

#define sipType_QPainter sipImportedTypes_pyqcamotorgui_QtGui[17].it_td
#define sipClass_QPainter sipImportedTypes_pyqcamotorgui_QtGui[17].it_td->u.td_wrapper_type

#define sipType_QPaintEngine sipImportedTypes_pyqcamotorgui_QtGui[15].it_td
#define sipClass_QPaintEngine sipImportedTypes_pyqcamotorgui_QtGui[15].it_td->u.td_wrapper_type
extern sipImportedTypeDef sipImportedTypes_pyqcamotorgui_QtGui[];

#define sipType_QWidget sipImportedTypes_pyqcamotorgui_QtWidgets[2].it_td
#define sipClass_QWidget sipImportedTypes_pyqcamotorgui_QtWidgets[2].it_td->u.td_wrapper_type

#define sipType_QPushButton sipImportedTypes_pyqcamotorgui_QtWidgets[1].it_td
#define sipClass_QPushButton sipImportedTypes_pyqcamotorgui_QtWidgets[1].it_td->u.td_wrapper_type

#define sipType_QDoubleSpinBox sipImportedTypes_pyqcamotorgui_QtWidgets[0].it_td
#define sipClass_QDoubleSpinBox sipImportedTypes_pyqcamotorgui_QtWidgets[0].it_td->u.td_wrapper_type
extern sipImportedTypeDef sipImportedTypes_pyqcamotorgui_QtWidgets[];

#define sipType_QCaMotor sipImportedTypes_pyqcamotorgui_pyqcamotor[0].it_td
#define sipClass_QCaMotor sipImportedTypes_pyqcamotorgui_pyqcamotor[0].it_td->u.td_wrapper_type
extern sipImportedTypeDef sipImportedTypes_pyqcamotorgui_pyqcamotor[];

typedef const QMetaObject *(*sip_qt_metaobject_func)(sipSimpleWrapper *,sipTypeDef *);
extern sip_qt_metaobject_func sip_pyqcamotorgui_qt_metaobject;

typedef int (*sip_qt_metacall_func)(sipSimpleWrapper *,sipTypeDef *,QMetaObject::Call,int,void **);
extern sip_qt_metacall_func sip_pyqcamotorgui_qt_metacall;

typedef bool (*sip_qt_metacast_func)(sipSimpleWrapper *, const sipTypeDef *, const char *, void **);
extern sip_qt_metacast_func sip_pyqcamotorgui_qt_metacast;

#endif
