/*
 * Internal module API header file.
 *
 * Generated by SIP 4.19.12
 */

#ifndef _qmotorstackAPI_H
#define _qmotorstackAPI_H

#include <sip.h>

#include <QMetaType>
#include <QThread>

/* These are the qualifiers that are enabled. */
#define SIP_FEATURE_PyQt_MacOSXOnly
#define SIP_FEATURE_PyQt_Process
#define SIP_FEATURE_PyQt_NotBootstrapped
#define SIP_FEATURE_PyQt_Desktop_OpenGL
#define SIP_FEATURE_PyQt_OpenGL
#define SIP_FEATURE_PyQt_RawFont
#define SIP_FEATURE_PyQt_PrintPreviewDialog
#define SIP_FEATURE_PyQt_PrintPreviewWidget
#define SIP_FEATURE_PyQt_Printer
#define SIP_FEATURE_PyQt_PrintDialog
#define SIP_FEATURE_Py_v3
#define SIP_FEATURE_PyQt_qreal_double
#define SIP_FEATURE_PyQt_SSL
#define SIP_FEATURE_PyQt_SessionManager
#define SIP_FEATURE_PyQt_Accessibility
#define SIP_PLATFORM_WS_X11


/*
 * Convenient names to refer to various strings defined in this module.
 * Only the class names are part of the public API.
 */
#define sipNameNr_mouseDoubleClickEvent 0
#define sipName_mouseDoubleClickEvent &sipStrings_qmotorstack[0]
#define sipNameNr_22 22
#define sipName_22 &sipStrings_qmotorstack[22]
#define sipNameNr_focusPreviousChild 42
#define sipName_focusPreviousChild &sipStrings_qmotorstack[42]
#define sipNameNr_focusNextPrevChild 61
#define sipName_focusNextPrevChild &sipStrings_qmotorstack[61]
#define sipNameNr_destroySubWindows 80
#define sipName_destroySubWindows &sipStrings_qmotorstack[80]
#define sipNameNr_hasHeightForWidth 98
#define sipName_hasHeightForWidth &sipStrings_qmotorstack[98]
#define sipNameNr_mouseReleaseEvent 116
#define sipName_mouseReleaseEvent &sipStrings_qmotorstack[116]
#define sipNameNr_loadConfiguration 134
#define sipName_loadConfiguration &sipStrings_qmotorstack[134]
#define sipNameNr_saveConfiguration 152
#define sipName_saveConfiguration &sipStrings_qmotorstack[152]
#define sipNameNr_isSignalConnected 170
#define sipName_isSignalConnected &sipStrings_qmotorstack[170]
#define sipNameNr_senderSignalIndex 188
#define sipName_senderSignalIndex &sipStrings_qmotorstack[188]
#define sipNameNr_206 206
#define sipName_206 &sipStrings_qmotorstack[206]
#define sipNameNr_destroyOldWindow 223
#define sipName_destroyOldWindow &sipStrings_qmotorstack[223]
#define sipNameNr_initializeWindow 240
#define sipName_initializeWindow &sipStrings_qmotorstack[240]
#define sipNameNr_updateMicroFocus 257
#define sipName_updateMicroFocus &sipStrings_qmotorstack[257]
#define sipNameNr_contextMenuEvent 274
#define sipName_contextMenuEvent &sipStrings_qmotorstack[274]
#define sipNameNr_inputMethodEvent 291
#define sipName_inputMethodEvent &sipStrings_qmotorstack[291]
#define sipNameNr_inputMethodQuery 308
#define sipName_inputMethodQuery &sipStrings_qmotorstack[308]
#define sipNameNr_disconnectNotify 325
#define sipName_disconnectNotify &sipStrings_qmotorstack[325]
#define sipNameNr_minimumSizeHint 342
#define sipName_minimumSizeHint &sipStrings_qmotorstack[342]
#define sipNameNr_mousePressEvent 358
#define sipName_mousePressEvent &sipStrings_qmotorstack[358]
#define sipNameNr_keyReleaseEvent 374
#define sipName_keyReleaseEvent &sipStrings_qmotorstack[374]
#define sipNameNr_deviceTransform 390
#define sipName_deviceTransform &sipStrings_qmotorstack[390]
#define sipNameNr_internal_format 406
#define sipName_internal_format &sipStrings_qmotorstack[406]
#define sipNameNr_aspectRatioMode 422
#define sipName_aspectRatioMode &sipStrings_qmotorstack[422]
#define sipNameNr_focusNextChild 438
#define sipName_focusNextChild &sipStrings_qmotorstack[438]
#define sipNameNr_heightForWidth 453
#define sipName_heightForWidth &sipStrings_qmotorstack[453]
#define sipNameNr_dragLeaveEvent 468
#define sipName_dragLeaveEvent &sipStrings_qmotorstack[468]
#define sipNameNr_dragEnterEvent 483
#define sipName_dragEnterEvent &sipStrings_qmotorstack[483]
#define sipNameNr_mouseMoveEvent 498
#define sipName_mouseMoveEvent &sipStrings_qmotorstack[498]
#define sipNameNr_changedSignal 513
#define sipName_changedSignal &sipStrings_qmotorstack[513]
#define sipNameNr_sharedPainter 527
#define sipName_sharedPainter &sipStrings_qmotorstack[527]
#define sipNameNr_destroyWindow 541
#define sipName_destroyWindow &sipStrings_qmotorstack[541]
#define sipNameNr_thresholdTime 555
#define sipName_thresholdTime &sipStrings_qmotorstack[555]
#define sipNameNr_dragMoveEvent 569
#define sipName_dragMoveEvent &sipStrings_qmotorstack[569]
#define sipNameNr_keyPressEvent 583
#define sipName_keyPressEvent &sipStrings_qmotorstack[583]
#define sipNameNr_focusOutEvent 597
#define sipName_focusOutEvent &sipStrings_qmotorstack[597]
#define sipNameNr_transformMode 611
#define sipName_transformMode &sipStrings_qmotorstack[611]
#define sipNameNr_connectNotify 328
#define sipName_connectNotify &sipStrings_qmotorstack[328]
#define sipNameNr_sourceRegion 625
#define sipName_sourceRegion &sipStrings_qmotorstack[625]
#define sipNameNr_targetOffset 638
#define sipName_targetOffset &sipStrings_qmotorstack[638]
#define sipNameNr_midLineWidth 651
#define sipName_midLineWidth &sipStrings_qmotorstack[651]
#define sipNameNr_focusInEvent 664
#define sipName_focusInEvent &sipStrings_qmotorstack[664]
#define sipNameNr_boundingRect 677
#define sipName_boundingRect &sipStrings_qmotorstack[677]
#define sipNameNr_listChanged 690
#define sipName_listChanged &sipStrings_qmotorstack[690]
#define sipNameNr_removeMotor 702
#define sipName_removeMotor &sipStrings_qmotorstack[702]
#define sipNameNr_showGeneral 714
#define sipName_showGeneral &sipStrings_qmotorstack[714]
#define sipNameNr_QMotorStack 726
#define sipName_QMotorStack &sipStrings_qmotorstack[726]
#define sipNameNr_initPainter 738
#define sipName_initPainter &sipStrings_qmotorstack[738]
#define sipNameNr_nativeEvent 750
#define sipName_nativeEvent &sipStrings_qmotorstack[750]
#define sipNameNr_actionEvent 762
#define sipName_actionEvent &sipStrings_qmotorstack[762]
#define sipNameNr_changeEvent 774
#define sipName_changeEvent &sipStrings_qmotorstack[774]
#define sipNameNr_tabletEvent 786
#define sipName_tabletEvent &sipStrings_qmotorstack[786]
#define sipNameNr_matchPolicy 798
#define sipName_matchPolicy &sipStrings_qmotorstack[798]
#define sipNameNr_resizeEvent 810
#define sipName_resizeEvent &sipStrings_qmotorstack[810]
#define sipNameNr_paintEngine 822
#define sipName_paintEngine &sipStrings_qmotorstack[822]
#define sipNameNr_customEvent 834
#define sipName_customEvent &sipStrings_qmotorstack[834]
#define sipNameNr_eventFilter 846
#define sipName_eventFilter &sipStrings_qmotorstack[846]
#define sipNameNr_qmotorstack 858
#define sipName_qmotorstack &sipStrings_qmotorstack[858]
#define sipNameNr_enterEvent 870
#define sipName_enterEvent &sipStrings_qmotorstack[870]
#define sipNameNr_leaveEvent 881
#define sipName_leaveEvent &sipStrings_qmotorstack[881]
#define sipNameNr_constraint 892
#define sipName_constraint &sipStrings_qmotorstack[892]
#define sipNameNr_closeEvent 903
#define sipName_closeEvent &sipStrings_qmotorstack[903]
#define sipNameNr_repeatTime 914
#define sipName_repeatTime &sipStrings_qmotorstack[914]
#define sipNameNr_wheelEvent 925
#define sipName_wheelEvent &sipStrings_qmotorstack[925]
#define sipNameNr_columnSpan 936
#define sipName_columnSpan &sipStrings_qmotorstack[936]
#define sipNameNr_paintEvent 947
#define sipName_paintEvent &sipStrings_qmotorstack[947]
#define sipNameNr_genMipMaps 958
#define sipName_genMipMaps &sipStrings_qmotorstack[958]
#define sipNameNr_setVisible 969
#define sipName_setVisible &sipStrings_qmotorstack[969]
#define sipNameNr_childEvent 980
#define sipName_childEvent &sipStrings_qmotorstack[980]
#define sipNameNr_timerEvent 991
#define sipName_timerEvent &sipStrings_qmotorstack[991]
#define sipNameNr_motorList 1002
#define sipName_motorList &sipStrings_qmotorstack[1002]
#define sipNameNr_dropEvent 1012
#define sipName_dropEvent &sipStrings_qmotorstack[1012]
#define sipNameNr_hideEvent 1022
#define sipName_hideEvent &sipStrings_qmotorstack[1022]
#define sipNameNr_showEvent 1032
#define sipName_showEvent &sipStrings_qmotorstack[1032]
#define sipNameNr_moveEvent 1042
#define sipName_moveEvent &sipStrings_qmotorstack[1042]
#define sipNameNr_operation 1052
#define sipName_operation &sipStrings_qmotorstack[1052]
#define sipNameNr_lineWidth 1062
#define sipName_lineWidth &sipStrings_qmotorstack[1062]
#define sipNameNr_directory 1072
#define sipName_directory &sipStrings_qmotorstack[1072]
#define sipNameNr_alignment 1082
#define sipName_alignment &sipStrings_qmotorstack[1082]
#define sipNameNr_receivers 1092
#define sipName_receivers &sipStrings_qmotorstack[1092]
#define sipNameNr_precision 1102
#define sipName_precision &sipStrings_qmotorstack[1102]
#define sipNameNr_addMotor 1112
#define sipName_addMotor &sipStrings_qmotorstack[1112]
#define sipNameNr_shortcut 1121
#define sipName_shortcut &sipStrings_qmotorstack[1121]
#define sipNameNr_userData 1130
#define sipName_userData &sipStrings_qmotorstack[1130]
#define sipNameNr_sizeHint 1139
#define sipName_sizeHint &sipStrings_qmotorstack[1139]
#define sipNameNr_fillRule 1148
#define sipName_fillRule &sipStrings_qmotorstack[1148]
#define sipNameNr_tabArray 1157
#define sipName_tabArray &sipStrings_qmotorstack[1157]
#define sipNameNr_tabStops 1166
#define sipName_tabStops &sipStrings_qmotorstack[1166]
#define sipNameNr_nameType 1175
#define sipName_nameType &sipStrings_qmotorstack[1175]
#define sipNameNr_position 1184
#define sipName_position &sipStrings_qmotorstack[1184]
#define sipNameNr_property 1193
#define sipName_property &sipStrings_qmotorstack[1193]
#define sipNameNr_isLocked 1202
#define sipName_isLocked &sipStrings_qmotorstack[1202]
#define sipNameNr_yMargin 1211
#define sipName_yMargin &sipStrings_qmotorstack[1211]
#define sipNameNr_xMargin 1219
#define sipName_xMargin &sipStrings_qmotorstack[1219]
#define sipNameNr_rowSpan 1227
#define sipName_rowSpan &sipStrings_qmotorstack[1227]
#define sipNameNr_exposed 1235
#define sipName_exposed &sipStrings_qmotorstack[1235]
#define sipNameNr_buffers 1243
#define sipName_buffers &sipStrings_qmotorstack[1243]
#define sipNameNr_sources 1251
#define sipName_sources &sipStrings_qmotorstack[1251]
#define sipNameNr_destroy 1259
#define sipName_destroy &sipStrings_qmotorstack[1259]
#define sipNameNr_quality 1267
#define sipName_quality &sipStrings_qmotorstack[1267]
#define sipNameNr_devType 1275
#define sipName_devType &sipStrings_qmotorstack[1275]
#define sipNameNr_filters 1283
#define sipName_filters &sipStrings_qmotorstack[1283]
#define sipNameNr_enabled 1291
#define sipName_enabled &sipStrings_qmotorstack[1291]
#define sipNameNr_options 1299
#define sipName_options &sipStrings_qmotorstack[1299]
#define sipNameNr_sunken 1307
#define sipName_sunken &sipStrings_qmotorstack[1307]
#define sipNameNr_layers 1314
#define sipName_layers &sipStrings_qmotorstack[1314]
#define sipNameNr_stride 1321
#define sipName_stride &sipStrings_qmotorstack[1321]
#define sipNameNr_metric 1328
#define sipName_metric &sipStrings_qmotorstack[1328]
#define sipNameNr_window 1335
#define sipName_window &sipStrings_qmotorstack[1335]
#define sipNameNr_create 1342
#define sipName_create &sipStrings_qmotorstack[1342]
#define sipNameNr_proper 1349
#define sipName_proper &sipStrings_qmotorstack[1349]
#define sipNameNr_sender 1356
#define sipName_sender &sipStrings_qmotorstack[1356]
#define sipNameNr_value9 1363
#define sipName_value9 &sipStrings_qmotorstack[1363]
#define sipNameNr_value8 1370
#define sipName_value8 &sipStrings_qmotorstack[1370]
#define sipNameNr_value7 1377
#define sipName_value7 &sipStrings_qmotorstack[1377]
#define sipNameNr_value6 1384
#define sipName_value6 &sipStrings_qmotorstack[1384]
#define sipNameNr_value5 1391
#define sipName_value5 &sipStrings_qmotorstack[1391]
#define sipNameNr_value4 1398
#define sipName_value4 &sipStrings_qmotorstack[1398]
#define sipNameNr_value3 1405
#define sipName_value3 &sipStrings_qmotorstack[1405]
#define sipNameNr_value2 1412
#define sipName_value2 &sipStrings_qmotorstack[1412]
#define sipNameNr_value1 1419
#define sipName_value1 &sipStrings_qmotorstack[1419]
#define sipNameNr_value0 1426
#define sipName_value0 &sipStrings_qmotorstack[1426]
#define sipNameNr_system 1433
#define sipName_system &sipStrings_qmotorstack[1433]
#define sipNameNr_symbol 1440
#define sipName_symbol &sipStrings_qmotorstack[1440]
#define sipNameNr_suffix 1447
#define sipName_suffix &sipStrings_qmotorstack[1447]
#define sipNameNr_offset 1454
#define sipName_offset &sipStrings_qmotorstack[1454]
#define sipNameNr_prefix 1461
#define sipName_prefix &sipStrings_qmotorstack[1461]
#define sipNameNr_filter 1468
#define sipName_filter &sipStrings_qmotorstack[1468]
#define sipNameNr_option 1475
#define sipName_option &sipStrings_qmotorstack[1475]
#define sipNameNr_locale 1482
#define sipName_locale &sipStrings_qmotorstack[1482]
#define sipNameNr_format 415
#define sipName_format &sipStrings_qmotorstack[415]
#define sipNameNr_column 1489
#define sipName_column &sipStrings_qmotorstack[1489]
#define sipNameNr_object 1496
#define sipName_object &sipStrings_qmotorstack[1496]
#define sipNameNr_parent 1503
#define sipName_parent &sipStrings_qmotorstack[1503]
#define sipNameNr_brush 1510
#define sipName_brush &sipStrings_qmotorstack[1510]
#define sipNameNr_types 1516
#define sipName_types &sipStrings_qmotorstack[1516]
#define sipNameNr_clear 1522
#define sipName_clear &sipStrings_qmotorstack[1522]
#define sipNameNr_order 1528
#define sipName_order &sipStrings_qmotorstack[1528]
#define sipNameNr_roles 1534
#define sipName_roles &sipStrings_qmotorstack[1534]
#define sipNameNr_flags 1540
#define sipName_flags &sipStrings_qmotorstack[1540]
#define sipNameNr_event 1546
#define sipName_event &sipStrings_qmotorstack[1546]
#define sipNameNr_msecs 1552
#define sipName_msecs &sipStrings_qmotorstack[1552]
#define sipNameNr_state 1558
#define sipName_state &sipStrings_qmotorstack[1558]
#define sipNameNr_lock 1564
#define sipName_lock &sipStrings_qmotorstack[1564]
#define sipNameNr_mode 1569
#define sipName_mode &sipStrings_qmotorstack[1569]
#define sipNameNr_name 1574
#define sipName_name &sipStrings_qmotorstack[1574]
#define sipNameNr_base 1579
#define sipName_base &sipStrings_qmotorstack[1579]
#define sipNameNr_fill 1584
#define sipName_fill &sipStrings_qmotorstack[1584]
#define sipNameNr_from 1589
#define sipName_from &sipStrings_qmotorstack[1589]
#define sipNameNr_sort 1594
#define sipName_sort &sipStrings_qmotorstack[1594]
#define sipNameNr_pen 1599
#define sipName_pen &sipStrings_qmotorstack[1599]
#define sipNameNr_pid 1603
#define sipName_pid &sipStrings_qmotorstack[1603]
#define sipNameNr_pos 1607
#define sipName_pos &sipStrings_qmotorstack[1607]
#define sipNameNr_sw 1611
#define sipName_sw &sipStrings_qmotorstack[1611]
#define sipNameNr_sh 1513
#define sipName_sh &sipStrings_qmotorstack[1513]
#define sipNameNr_sy 1614
#define sipName_sy &sipStrings_qmotorstack[1614]
#define sipNameNr_sx 1617
#define sipName_sx &sipStrings_qmotorstack[1617]
#define sipNameNr_at 419
#define sipName_at &sipStrings_qmotorstack[419]

#define sipMalloc                   sipAPI_qmotorstack->api_malloc
#define sipFree                     sipAPI_qmotorstack->api_free
#define sipBuildResult              sipAPI_qmotorstack->api_build_result
#define sipCallMethod               sipAPI_qmotorstack->api_call_method
#define sipCallProcedureMethod      sipAPI_qmotorstack->api_call_procedure_method
#define sipCallErrorHandler         sipAPI_qmotorstack->api_call_error_handler
#define sipParseResultEx            sipAPI_qmotorstack->api_parse_result_ex
#define sipParseResult              sipAPI_qmotorstack->api_parse_result
#define sipParseArgs                sipAPI_qmotorstack->api_parse_args
#define sipParseKwdArgs             sipAPI_qmotorstack->api_parse_kwd_args
#define sipParsePair                sipAPI_qmotorstack->api_parse_pair
#define sipInstanceDestroyed        sipAPI_qmotorstack->api_instance_destroyed
#define sipInstanceDestroyedEx      sipAPI_qmotorstack->api_instance_destroyed_ex
#define sipConvertFromSequenceIndex sipAPI_qmotorstack->api_convert_from_sequence_index
#define sipConvertFromSliceObject   sipAPI_qmotorstack->api_convert_from_slice_object
#define sipConvertFromVoidPtr       sipAPI_qmotorstack->api_convert_from_void_ptr
#define sipConvertToVoidPtr         sipAPI_qmotorstack->api_convert_to_void_ptr
#define sipAddException             sipAPI_qmotorstack->api_add_exception
#define sipNoFunction               sipAPI_qmotorstack->api_no_function
#define sipNoMethod                 sipAPI_qmotorstack->api_no_method
#define sipAbstractMethod           sipAPI_qmotorstack->api_abstract_method
#define sipBadClass                 sipAPI_qmotorstack->api_bad_class
#define sipBadCatcherResult         sipAPI_qmotorstack->api_bad_catcher_result
#define sipBadCallableArg           sipAPI_qmotorstack->api_bad_callable_arg
#define sipBadOperatorArg           sipAPI_qmotorstack->api_bad_operator_arg
#define sipTrace                    sipAPI_qmotorstack->api_trace
#define sipTransferBack             sipAPI_qmotorstack->api_transfer_back
#define sipTransferTo               sipAPI_qmotorstack->api_transfer_to
#define sipTransferBreak            sipAPI_qmotorstack->api_transfer_break
#define sipSimpleWrapper_Type       sipAPI_qmotorstack->api_simplewrapper_type
#define sipWrapper_Type             sipAPI_qmotorstack->api_wrapper_type
#define sipWrapperType_Type         sipAPI_qmotorstack->api_wrappertype_type
#define sipVoidPtr_Type             sipAPI_qmotorstack->api_voidptr_type
#define sipGetPyObject              sipAPI_qmotorstack->api_get_pyobject
#define sipGetAddress               sipAPI_qmotorstack->api_get_address
#define sipGetMixinAddress          sipAPI_qmotorstack->api_get_mixin_address
#define sipGetCppPtr                sipAPI_qmotorstack->api_get_cpp_ptr
#define sipGetComplexCppPtr         sipAPI_qmotorstack->api_get_complex_cpp_ptr
#define sipIsPyMethod               sipAPI_qmotorstack->api_is_py_method
#define sipCallHook                 sipAPI_qmotorstack->api_call_hook
#define sipEndThread                sipAPI_qmotorstack->api_end_thread
#define sipConnectRx                sipAPI_qmotorstack->api_connect_rx
#define sipDisconnectRx             sipAPI_qmotorstack->api_disconnect_rx
#define sipRaiseUnknownException    sipAPI_qmotorstack->api_raise_unknown_exception
#define sipRaiseTypeException       sipAPI_qmotorstack->api_raise_type_exception
#define sipBadLengthForSlice        sipAPI_qmotorstack->api_bad_length_for_slice
#define sipAddTypeInstance          sipAPI_qmotorstack->api_add_type_instance
#define sipFreeSipslot              sipAPI_qmotorstack->api_free_sipslot
#define sipSameSlot                 sipAPI_qmotorstack->api_same_slot
#define sipPySlotExtend             sipAPI_qmotorstack->api_pyslot_extend
#define sipConvertRx                sipAPI_qmotorstack->api_convert_rx
#define sipAddDelayedDtor           sipAPI_qmotorstack->api_add_delayed_dtor
#define sipCanConvertToType         sipAPI_qmotorstack->api_can_convert_to_type
#define sipConvertToType            sipAPI_qmotorstack->api_convert_to_type
#define sipForceConvertToType       sipAPI_qmotorstack->api_force_convert_to_type
#define sipCanConvertToEnum         sipAPI_qmotorstack->api_can_convert_to_enum
#define sipConvertToEnum            sipAPI_qmotorstack->api_convert_to_enum
#define sipConvertToBool            sipAPI_qmotorstack->api_convert_to_bool
#define sipReleaseType              sipAPI_qmotorstack->api_release_type
#define sipConvertFromType          sipAPI_qmotorstack->api_convert_from_type
#define sipConvertFromNewType       sipAPI_qmotorstack->api_convert_from_new_type
#define sipConvertFromNewPyType     sipAPI_qmotorstack->api_convert_from_new_pytype
#define sipConvertFromEnum          sipAPI_qmotorstack->api_convert_from_enum
#define sipGetState                 sipAPI_qmotorstack->api_get_state
#define sipExportSymbol             sipAPI_qmotorstack->api_export_symbol
#define sipImportSymbol             sipAPI_qmotorstack->api_import_symbol
#define sipFindType                 sipAPI_qmotorstack->api_find_type
#define sipFindNamedEnum            sipAPI_qmotorstack->api_find_named_enum
#define sipBytes_AsChar             sipAPI_qmotorstack->api_bytes_as_char
#define sipBytes_AsString           sipAPI_qmotorstack->api_bytes_as_string
#define sipString_AsASCIIChar       sipAPI_qmotorstack->api_string_as_ascii_char
#define sipString_AsASCIIString     sipAPI_qmotorstack->api_string_as_ascii_string
#define sipString_AsLatin1Char      sipAPI_qmotorstack->api_string_as_latin1_char
#define sipString_AsLatin1String    sipAPI_qmotorstack->api_string_as_latin1_string
#define sipString_AsUTF8Char        sipAPI_qmotorstack->api_string_as_utf8_char
#define sipString_AsUTF8String      sipAPI_qmotorstack->api_string_as_utf8_string
#define sipUnicode_AsWChar          sipAPI_qmotorstack->api_unicode_as_wchar
#define sipUnicode_AsWString        sipAPI_qmotorstack->api_unicode_as_wstring
#define sipConvertFromConstVoidPtr  sipAPI_qmotorstack->api_convert_from_const_void_ptr
#define sipConvertFromVoidPtrAndSize    sipAPI_qmotorstack->api_convert_from_void_ptr_and_size
#define sipConvertFromConstVoidPtrAndSize   sipAPI_qmotorstack->api_convert_from_const_void_ptr_and_size
#define sipInvokeSlot               sipAPI_qmotorstack->api_invoke_slot
#define sipInvokeSlotEx             sipAPI_qmotorstack->api_invoke_slot_ex
#define sipSaveSlot                 sipAPI_qmotorstack->api_save_slot
#define sipClearAnySlotReference    sipAPI_qmotorstack->api_clear_any_slot_reference
#define sipVisitSlot                sipAPI_qmotorstack->api_visit_slot
#define sipWrappedTypeName(wt)      ((wt)->wt_td->td_cname)
#define sipDeprecated               sipAPI_qmotorstack->api_deprecated
#define sipGetReference             sipAPI_qmotorstack->api_get_reference
#define sipKeepReference            sipAPI_qmotorstack->api_keep_reference
#define sipRegisterProxyResolver    sipAPI_qmotorstack->api_register_proxy_resolver
#define sipRegisterPyType           sipAPI_qmotorstack->api_register_py_type
#define sipTypeFromPyTypeObject     sipAPI_qmotorstack->api_type_from_py_type_object
#define sipTypeScope                sipAPI_qmotorstack->api_type_scope
#define sipResolveTypedef           sipAPI_qmotorstack->api_resolve_typedef
#define sipRegisterAttributeGetter  sipAPI_qmotorstack->api_register_attribute_getter
#define sipIsAPIEnabled             sipAPI_qmotorstack->api_is_api_enabled
#define sipSetDestroyOnExit         sipAPI_qmotorstack->api_set_destroy_on_exit
#define sipEnableAutoconversion     sipAPI_qmotorstack->api_enable_autoconversion
#define sipEnableOverflowChecking   sipAPI_qmotorstack->api_enable_overflow_checking
#define sipInitMixin                sipAPI_qmotorstack->api_init_mixin
#define sipExportModule             sipAPI_qmotorstack->api_export_module
#define sipInitModule               sipAPI_qmotorstack->api_init_module
#define sipGetInterpreter           sipAPI_qmotorstack->api_get_interpreter
#define sipSetNewUserTypeHandler    sipAPI_qmotorstack->api_set_new_user_type_handler
#define sipSetTypeUserData          sipAPI_qmotorstack->api_set_type_user_data
#define sipGetTypeUserData          sipAPI_qmotorstack->api_get_type_user_data
#define sipPyTypeDict               sipAPI_qmotorstack->api_py_type_dict
#define sipPyTypeName               sipAPI_qmotorstack->api_py_type_name
#define sipGetCFunction             sipAPI_qmotorstack->api_get_c_function
#define sipGetMethod                sipAPI_qmotorstack->api_get_method
#define sipFromMethod               sipAPI_qmotorstack->api_from_method
#define sipGetDate                  sipAPI_qmotorstack->api_get_date
#define sipFromDate                 sipAPI_qmotorstack->api_from_date
#define sipGetDateTime              sipAPI_qmotorstack->api_get_datetime
#define sipFromDateTime             sipAPI_qmotorstack->api_from_datetime
#define sipGetTime                  sipAPI_qmotorstack->api_get_time
#define sipFromTime                 sipAPI_qmotorstack->api_from_time
#define sipIsUserType               sipAPI_qmotorstack->api_is_user_type
#define sipGetFrame                 sipAPI_qmotorstack->api_get_frame
#define sipCheckPluginForType       sipAPI_qmotorstack->api_check_plugin_for_type
#define sipUnicodeNew               sipAPI_qmotorstack->api_unicode_new
#define sipUnicodeWrite             sipAPI_qmotorstack->api_unicode_write
#define sipUnicodeData              sipAPI_qmotorstack->api_unicode_data
#define sipGetBufferInfo            sipAPI_qmotorstack->api_get_buffer_info
#define sipReleaseBufferInfo        sipAPI_qmotorstack->api_release_buffer_info
#define sipIsOwnedByPython          sipAPI_qmotorstack->api_is_owned_by_python
#define sipIsDerivedClass           sipAPI_qmotorstack->api_is_derived_class
#define sipGetUserObject            sipAPI_qmotorstack->api_get_user_object
#define sipSetUserObject            sipAPI_qmotorstack->api_set_user_object
#define sipRegisterEventHandler     sipAPI_qmotorstack->api_register_event_handler
#define sipLong_AsChar              sipAPI_qmotorstack->api_long_as_char
#define sipLong_AsSignedChar        sipAPI_qmotorstack->api_long_as_signed_char
#define sipLong_AsUnsignedChar      sipAPI_qmotorstack->api_long_as_unsigned_char
#define sipLong_AsShort             sipAPI_qmotorstack->api_long_as_short
#define sipLong_AsUnsignedShort     sipAPI_qmotorstack->api_long_as_unsigned_short
#define sipLong_AsInt               sipAPI_qmotorstack->api_long_as_int
#define sipLong_AsUnsignedInt       sipAPI_qmotorstack->api_long_as_unsigned_int
#define sipLong_AsLong              sipAPI_qmotorstack->api_long_as_long
#define sipLong_AsUnsignedLong      sipAPI_qmotorstack->api_long_as_unsigned_long
#define sipLong_AsLongLong          sipAPI_qmotorstack->api_long_as_long_long
#define sipLong_AsUnsignedLongLong  sipAPI_qmotorstack->api_long_as_unsigned_long_long

/* These are deprecated. */
#define sipMapStringToClass         sipAPI_qmotorstack->api_map_string_to_class
#define sipMapIntToClass            sipAPI_qmotorstack->api_map_int_to_class
#define sipFindClass                sipAPI_qmotorstack->api_find_class
#define sipFindMappedType           sipAPI_qmotorstack->api_find_mapped_type
#define sipConvertToArray           sipAPI_qmotorstack->api_convert_to_array
#define sipConvertToTypedArray      sipAPI_qmotorstack->api_convert_to_typed_array
#define sipEnableGC                 sipAPI_qmotorstack->api_enable_gc
#define sipPrintObject              sipAPI_qmotorstack->api_print_object
#define sipWrapper_Check(w)         PyObject_TypeCheck((w), sipAPI_qmotorstack->api_wrapper_type)
#define sipGetWrapper(p, wt)        sipGetPyObject((p), (wt)->wt_td)
#define sipReleaseInstance(p, wt, s)    sipReleaseType((p), (wt)->wt_td, (s))
#define sipReleaseMappedType        sipReleaseType
#define sipCanConvertToInstance(o, wt, f)   sipCanConvertToType((o), (wt)->wt_td, (f))
#define sipCanConvertToMappedType   sipCanConvertToType
#define sipConvertToInstance(o, wt, t, f, s, e)     sipConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipConvertToMappedType      sipConvertToType
#define sipForceConvertToInstance(o, wt, t, f, s, e)    sipForceConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipForceConvertToMappedType sipForceConvertToType
#define sipConvertFromInstance(p, wt, t)    sipConvertFromType((p), (wt)->wt_td, (t))
#define sipConvertFromMappedType    sipConvertFromType
#define sipConvertFromNamedEnum(v, pt)  sipConvertFromEnum((v), ((sipEnumTypeObject *)(pt))->type)
#define sipConvertFromNewInstance(p, wt, t) sipConvertFromNewType((p), (wt)->wt_td, (t))

/* The strings used by this module. */
extern const char sipStrings_qmotorstack[];

#define sipType_QMotorStack sipExportedTypes_qmotorstack[2]
#define sipClass_QMotorStack sipExportedTypes_qmotorstack[2]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_qmotorstack_QMotorStack;

#define sipType_QList_0101QCaMotor sipExportedTypes_qmotorstack[0]

extern sipMappedTypeDef sipTypeDef_qmotorstack_QList_0101QCaMotor;

#define sipType_QList_0101QCaMotorGUI sipExportedTypes_qmotorstack[1]

extern sipMappedTypeDef sipTypeDef_qmotorstack_QList_0101QCaMotorGUI;

/* The SIP API, this module's API and the APIs of any imported modules. */
extern const sipAPIDef *sipAPI_qmotorstack;
extern sipExportedModuleDef sipModuleAPI_qmotorstack;
extern sipTypeDef *sipExportedTypes_qmotorstack[];

#define sipType_Qt_InputMethodQuery sipImportedTypes_qmotorstack_QtCore[10].it_td
#define sipEnum_Qt_InputMethodQuery sipImportedTypes_qmotorstack_QtCore[10].it_td->u.td_py_type

#define sipType_QObject sipImportedTypes_qmotorstack_QtCore[4].it_td
#define sipClass_QObject sipImportedTypes_qmotorstack_QtCore[4].it_td->u.td_wrapper_type

#define sipType_QByteArray sipImportedTypes_qmotorstack_QtCore[0].it_td
#define sipClass_QByteArray sipImportedTypes_qmotorstack_QtCore[0].it_td->u.td_wrapper_type

#define sipType_QEvent sipImportedTypes_qmotorstack_QtCore[2].it_td
#define sipClass_QEvent sipImportedTypes_qmotorstack_QtCore[2].it_td->u.td_wrapper_type

#define sipType_QTimerEvent sipImportedTypes_qmotorstack_QtCore[8].it_td
#define sipClass_QTimerEvent sipImportedTypes_qmotorstack_QtCore[8].it_td->u.td_wrapper_type

#define sipType_QChildEvent sipImportedTypes_qmotorstack_QtCore[1].it_td
#define sipClass_QChildEvent sipImportedTypes_qmotorstack_QtCore[1].it_td->u.td_wrapper_type

#define sipType_QMetaMethod sipImportedTypes_qmotorstack_QtCore[3].it_td
#define sipClass_QMetaMethod sipImportedTypes_qmotorstack_QtCore[3].it_td->u.td_wrapper_type

#define sipType_QSize sipImportedTypes_qmotorstack_QtCore[5].it_td
#define sipClass_QSize sipImportedTypes_qmotorstack_QtCore[5].it_td->u.td_wrapper_type

#define sipType_QVariant sipImportedTypes_qmotorstack_QtCore[9].it_td
#define sipClass_QVariant sipImportedTypes_qmotorstack_QtCore[9].it_td->u.td_wrapper_type

#define sipType_QStringList sipImportedTypes_qmotorstack_QtCore[7].it_td

#define sipType_QString sipImportedTypes_qmotorstack_QtCore[6].it_td

#define sipType_quintptr sipImportedTypes_qmotorstack_QtCore[11].it_td
extern sipImportedTypeDef sipImportedTypes_qmotorstack_QtCore[];
extern sipImportedVirtErrorHandlerDef sipImportedVirtErrorHandlers_qmotorstack_QtCore[];

#define sipType_QPaintDevice sipImportedTypes_qmotorstack_QtGui[13].it_td
#define sipClass_QPaintDevice sipImportedTypes_qmotorstack_QtGui[13].it_td->u.td_wrapper_type

#define sipType_QPaintDevice_PaintDeviceMetric sipImportedTypes_qmotorstack_QtGui[14].it_td
#define sipEnum_QPaintDevice_PaintDeviceMetric sipImportedTypes_qmotorstack_QtGui[14].it_td->u.td_py_type

#define sipType_QMouseEvent sipImportedTypes_qmotorstack_QtGui[11].it_td
#define sipClass_QMouseEvent sipImportedTypes_qmotorstack_QtGui[11].it_td->u.td_wrapper_type

#define sipType_QWheelEvent sipImportedTypes_qmotorstack_QtGui[21].it_td
#define sipClass_QWheelEvent sipImportedTypes_qmotorstack_QtGui[21].it_td->u.td_wrapper_type

#define sipType_QTabletEvent sipImportedTypes_qmotorstack_QtGui[20].it_td
#define sipClass_QTabletEvent sipImportedTypes_qmotorstack_QtGui[20].it_td->u.td_wrapper_type

#define sipType_QKeyEvent sipImportedTypes_qmotorstack_QtGui[10].it_td
#define sipClass_QKeyEvent sipImportedTypes_qmotorstack_QtGui[10].it_td->u.td_wrapper_type

#define sipType_QFocusEvent sipImportedTypes_qmotorstack_QtGui[7].it_td
#define sipClass_QFocusEvent sipImportedTypes_qmotorstack_QtGui[7].it_td->u.td_wrapper_type

#define sipType_QPaintEvent sipImportedTypes_qmotorstack_QtGui[16].it_td
#define sipClass_QPaintEvent sipImportedTypes_qmotorstack_QtGui[16].it_td->u.td_wrapper_type

#define sipType_QMoveEvent sipImportedTypes_qmotorstack_QtGui[12].it_td
#define sipClass_QMoveEvent sipImportedTypes_qmotorstack_QtGui[12].it_td->u.td_wrapper_type

#define sipType_QResizeEvent sipImportedTypes_qmotorstack_QtGui[18].it_td
#define sipClass_QResizeEvent sipImportedTypes_qmotorstack_QtGui[18].it_td->u.td_wrapper_type

#define sipType_QCloseEvent sipImportedTypes_qmotorstack_QtGui[1].it_td
#define sipClass_QCloseEvent sipImportedTypes_qmotorstack_QtGui[1].it_td->u.td_wrapper_type

#define sipType_QShowEvent sipImportedTypes_qmotorstack_QtGui[19].it_td
#define sipClass_QShowEvent sipImportedTypes_qmotorstack_QtGui[19].it_td->u.td_wrapper_type

#define sipType_QHideEvent sipImportedTypes_qmotorstack_QtGui[8].it_td
#define sipClass_QHideEvent sipImportedTypes_qmotorstack_QtGui[8].it_td->u.td_wrapper_type

#define sipType_QContextMenuEvent sipImportedTypes_qmotorstack_QtGui[2].it_td
#define sipClass_QContextMenuEvent sipImportedTypes_qmotorstack_QtGui[2].it_td->u.td_wrapper_type

#define sipType_QInputMethodEvent sipImportedTypes_qmotorstack_QtGui[9].it_td
#define sipClass_QInputMethodEvent sipImportedTypes_qmotorstack_QtGui[9].it_td->u.td_wrapper_type

#define sipType_QDropEvent sipImportedTypes_qmotorstack_QtGui[6].it_td
#define sipClass_QDropEvent sipImportedTypes_qmotorstack_QtGui[6].it_td->u.td_wrapper_type

#define sipType_QDragMoveEvent sipImportedTypes_qmotorstack_QtGui[5].it_td
#define sipClass_QDragMoveEvent sipImportedTypes_qmotorstack_QtGui[5].it_td->u.td_wrapper_type

#define sipType_QDragEnterEvent sipImportedTypes_qmotorstack_QtGui[3].it_td
#define sipClass_QDragEnterEvent sipImportedTypes_qmotorstack_QtGui[3].it_td->u.td_wrapper_type

#define sipType_QDragLeaveEvent sipImportedTypes_qmotorstack_QtGui[4].it_td
#define sipClass_QDragLeaveEvent sipImportedTypes_qmotorstack_QtGui[4].it_td->u.td_wrapper_type

#define sipType_QActionEvent sipImportedTypes_qmotorstack_QtGui[0].it_td
#define sipClass_QActionEvent sipImportedTypes_qmotorstack_QtGui[0].it_td->u.td_wrapper_type

#define sipType_QPainter sipImportedTypes_qmotorstack_QtGui[17].it_td
#define sipClass_QPainter sipImportedTypes_qmotorstack_QtGui[17].it_td->u.td_wrapper_type

#define sipType_QPaintEngine sipImportedTypes_qmotorstack_QtGui[15].it_td
#define sipClass_QPaintEngine sipImportedTypes_qmotorstack_QtGui[15].it_td->u.td_wrapper_type
extern sipImportedTypeDef sipImportedTypes_qmotorstack_QtGui[];

#define sipType_QWidget sipImportedTypes_qmotorstack_QtWidgets[0].it_td
#define sipClass_QWidget sipImportedTypes_qmotorstack_QtWidgets[0].it_td->u.td_wrapper_type
extern sipImportedTypeDef sipImportedTypes_qmotorstack_QtWidgets[];

#define sipType_QCaMotor sipImportedTypes_qmotorstack_qcamotor[0].it_td
#define sipClass_QCaMotor sipImportedTypes_qmotorstack_qcamotor[0].it_td->u.td_wrapper_type
extern sipImportedTypeDef sipImportedTypes_qmotorstack_qcamotor[];

#define sipType_QCaMotorGUI sipImportedTypes_qmotorstack_qcamotorgui[0].it_td
#define sipClass_QCaMotorGUI sipImportedTypes_qmotorstack_qcamotorgui[0].it_td->u.td_wrapper_type
extern sipImportedTypeDef sipImportedTypes_qmotorstack_qcamotorgui[];

typedef const QMetaObject *(*sip_qt_metaobject_func)(sipSimpleWrapper *,sipTypeDef *);
extern sip_qt_metaobject_func sip_qmotorstack_qt_metaobject;

typedef int (*sip_qt_metacall_func)(sipSimpleWrapper *,sipTypeDef *,QMetaObject::Call,int,void **);
extern sip_qt_metacall_func sip_qmotorstack_qt_metacall;

typedef bool (*sip_qt_metacast_func)(sipSimpleWrapper *, const sipTypeDef *, const char *, void **);
extern sip_qt_metacast_func sip_qmotorstack_qt_metacast;

#endif
