/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.19.16
 */

#include "sipAPIpyqmotorstack.h"

#line 149 "/usr/share/sip/PyQt5/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 12 "./sippyqmotorstackQList0101QCaMotor.cpp"

#line 12 "../qcamotor_py//pyqcamotor.sip"
#include "qcamotor.h"
#line 16 "./sippyqmotorstackQList0101QCaMotor.cpp"


extern "C" {static void assign_QList_0101QCaMotor(void *, SIP_SSIZE_T, void *);}
static void assign_QList_0101QCaMotor(void *sipDst, SIP_SSIZE_T sipDstIdx, void *sipSrc)
{
    reinterpret_cast<QList< ::QCaMotor*> *>(sipDst)[sipDstIdx] = *reinterpret_cast<QList< ::QCaMotor*> *>(sipSrc);
}


extern "C" {static void *array_QList_0101QCaMotor(SIP_SSIZE_T);}
static void *array_QList_0101QCaMotor(SIP_SSIZE_T sipNrElem)
{
    return new QList< ::QCaMotor*>[sipNrElem];
}


extern "C" {static void *copy_QList_0101QCaMotor(const void *, SIP_SSIZE_T);}
static void *copy_QList_0101QCaMotor(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new QList< ::QCaMotor*>(reinterpret_cast<const QList< ::QCaMotor*> *>(sipSrc)[sipSrcIdx]);
}


/* Call the mapped type's destructor. */
extern "C" {static void release_QList_0101QCaMotor(void *, int);}
static void release_QList_0101QCaMotor(void *ptr, int)
{
    delete reinterpret_cast<QList< ::QCaMotor*> *>(ptr);
}



extern "C" {static int convertTo_QList_0101QCaMotor(PyObject *, void **, int *, PyObject *);}
static int convertTo_QList_0101QCaMotor(PyObject *sipPy,void **sipCppPtrV,int *sipIsErr,PyObject *sipTransferObj)
{
    QList< ::QCaMotor*> **sipCppPtr = reinterpret_cast<QList< ::QCaMotor*> **>(sipCppPtrV);

#line 184 "/usr/share/sip/PyQt5/QtCore/qpycore_qlist.sip"
    PyObject *iter = PyObject_GetIter(sipPy);

    if (!sipIsErr)
    {
        PyErr_Clear();
        Py_XDECREF(iter);

        return (iter
#if PY_MAJOR_VERSION < 3
                && !PyString_Check(sipPy)
#endif
                && !PyUnicode_Check(sipPy));
    }

    if (!iter)
    {
        *sipIsErr = 1;

        return 0;
    }

    QList<QCaMotor *> *ql = new QList<QCaMotor *>;
 
    for (Py_ssize_t i = 0; ; ++i)
    {
        PyErr_Clear();
        PyObject *itm = PyIter_Next(iter);

        if (!itm)
        {
            if (PyErr_Occurred())
            {
                delete ql;
                Py_DECREF(iter);
                *sipIsErr = 1;

                return 0;
            }

            break;
        }

        QCaMotor *t = reinterpret_cast<QCaMotor *>(
                sipForceConvertToType(itm, sipType_QCaMotor, sipTransferObj, 0,
                        0, sipIsErr));
 
        if (*sipIsErr)
        {
            PyErr_Format(PyExc_TypeError,
                    "index %zd has type '%s' but 'QCaMotor' is expected", i,
                    sipPyTypeName(Py_TYPE(itm)));

            Py_DECREF(itm);
            delete ql;
            Py_DECREF(iter);

            return 0;
        }

        ql->append(t);

        Py_DECREF(itm);
    }

    Py_DECREF(iter);
 
    *sipCppPtr = ql;
 
    return sipGetState(sipTransferObj);
#line 124 "./sippyqmotorstackQList0101QCaMotor.cpp"
}


extern "C" {static PyObject *convertFrom_QList_0101QCaMotor(void *, PyObject *);}
static PyObject *convertFrom_QList_0101QCaMotor(void *sipCppV, PyObject *sipTransferObj)
{
   QList< ::QCaMotor*> *sipCpp = reinterpret_cast<QList< ::QCaMotor*> *>(sipCppV);

#line 153 "/usr/share/sip/PyQt5/QtCore/qpycore_qlist.sip"
    int gc_enabled = sipEnableGC(0);
    PyObject *l = PyList_New(sipCpp->size());

    if (l)
    {
        for (int i = 0; i < sipCpp->size(); ++i)
        {
            QCaMotor *t = sipCpp->at(i);

            // The explicit (void *) cast allows QCaMotor to be const.
            PyObject *tobj = sipConvertFromType((void *)t, sipType_QCaMotor,
                    sipTransferObj);

            if (!tobj)
            {
                Py_DECREF(l);
                l = 0;

                break;
            }

            PyList_SetItem(l, i, tobj);
        }
    }

    sipEnableGC(gc_enabled);

    return l;
#line 162 "./sippyqmotorstackQList0101QCaMotor.cpp"
}


sipMappedTypeDef sipTypeDef_pyqmotorstack_QList_0101QCaMotor = {
    {
        -1,
        SIP_NULLPTR,
        0,
        SIP_TYPE_MAPPED,
        sipNameNr_206,     /* QList<QCaMotor*> */
        {0},
        0
    },
    {
        -1,
        {0, 0, 1},
        0, 0,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    },
    assign_QList_0101QCaMotor,
    array_QList_0101QCaMotor,
    copy_QList_0101QCaMotor,
    release_QList_0101QCaMotor,
    convertTo_QList_0101QCaMotor,
    convertFrom_QList_0101QCaMotor
};
